import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // All placeholder/product images are local, trusted SVGs generated by
    // scripts/generate-placeholder-images.mjs. Safe to allow SVG optimization
    // since no user-uploaded or remote content is served through next/image.
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    // Product photos use quality={90}/{95} for sharper rendering than the
    // Next.js default (75) allows, so those values must be explicitly permitted.
    qualities: [75, 90, 95],
  },
};

export default nextConfig;
