import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const SAFETY_STANDARD = [
  "Tested to ASTM F963 & EN71 safety standards",
  "Non-toxic, water-based paints and finishes",
  "No small parts hazard for stated age range",
];

interface SeedProduct {
  slug: string;
  name: string; nameHy: string; nameRu: string;
  shortDescription: string; shortDescriptionHy: string; shortDescriptionRu: string;
  description: string; descriptionHy: string; descriptionRu: string;
  priceAmd: number;
  compareAtPriceAmd?: number;
  category: string;
  subcategory: string;
  ageRange: string;
  materials: string[];
  safetyInfo: string[];
  brand: string;
  images: { src: string; alt: string }[];
  inStock: boolean;
  sku: string;
  featured?: boolean;
  bestseller?: boolean;
  newArrival?: boolean;
  relatedSlugs?: string[];
  dimensions?: string;
  weightGrams?: number;
  careInstructions?: string;
}

const products: SeedProduct[] = [
  {
    slug: "color-sorting-board",
    name: "Color Sorting Board with Pattern Cards",
    nameHy: "Գունային տեսակավորման տախտակ՝ նմուշի քարտերով",
    nameRu: "Доска для сортировки по цвету с карточками-образцами",
    shortDescription: "Wooden sorting board with layered color pieces and difficulty cards for beginners through advanced players.",
    shortDescriptionHy: "Փայտյա տեսակավորման տախտակ՝ գունավոր շերտավոր կտորներով և բարդության մակարդակի քարտերով։",
    shortDescriptionRu: "Деревянная доска для сортировки с многослойными цветными деталями и карточками разного уровня сложности.",
    description:
      "Four sliding rods hold stacks of colorful wooden shapes that children rearrange to match pattern cards, from simple two-color sequences to advanced combinations. Builds color recognition, sequencing, and concentration, and folds shut into its own wooden storage box.",
    descriptionHy:
      "Չորս սահող ձողեր պահում են գունավոր փայտյա ձևերի կույտեր, որոնք երեխաները վերադասավորում են՝ համապատասխանեցնելով նմուշի քարտերին՝ սկսած պարզ երկգույն հաջորդականություններից մինչև բարդ զուգակցումներ։ Զարգացնում է գույների ճանաչումը, հաջորդականությունը և կենտրոնացումը, և ծալվում է սեփական փայտյա արկղի մեջ։",
    descriptionRu:
      "Четыре подвижных стержня удерживают стопки цветных деревянных фигур, которые ребёнок переставляет по образцу карточек — от простых двухцветных последовательностей до сложных комбинаций. Развивает распознавание цвета, последовательное мышление и концентрацию, а сама доска складывается в собственную деревянную коробку для хранения.",
    priceAmd: 11800,
    category: "educational",
    subcategory: "early-learning",
    ageRange: "3-6",
    materials: ["Solid wood", "Cardboard pattern cards"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/color-sorting-board-1-v3.jpg", alt: "Wooden color sorting board with layered shapes and pattern cards" }, { src: "/images/products/color-sorting-board-2.jpg", alt: "Color sorting board with its wooden storage box open beside it" }, { src: "/images/products/color-sorting-board-3.jpg", alt: "Color sorting board and pattern cards, angled view showing the wooden case" }],
    inStock: true,
    sku: "58406",
    featured: true,
    relatedSlugs: ["rainbow-sorting-board", "counting-frame"],
    dimensions: "23.5 x 19.2 x 3.7 cm",
  },
  {
    slug: "rainbow-sorting-board",
    name: "Rainbow Color Sorting Board",
    nameHy: "Ծիածան գունային տեսակավորման տախտակ",
    nameRu: "Радужная доска для сортировки по цвету",
    shortDescription: "Simplified single-rainbow version of our classic color sorting board, sized for first learners.",
    shortDescriptionHy: "Մեր դասական գունային տեսակավորման տախտակի պարզեցված տարբերակը՝ հարմարեցված սկսնակների համար։",
    shortDescriptionRu: "Упрощённая радужная версия нашей классической доски для сортировки цветов — специально для самых маленьких.",
    description:
      "A gentler entry point into color sorting, with rainbow-toned wooden pieces threaded onto a single sturdy rod. Children slide, remove, and re-stack the colors freely, building color vocabulary and hand strength before moving on to pattern-matching challenges.",
    descriptionHy:
      "Գունային տեսակավորման ավելի մեղմ ներածություն՝ ծիածանագույն փայտյա կտորներով, որոնք անցկացված են մեկ ամուր ձողի վրա։ Երեխաները ազատորեն սահեցնում, հանում և վերադասավորում են գույները՝ զարգացնելով գունային բառապաշարը և ձեռքի ուժը՝ նախքան նմուշների համապատասխանեցման մարտահրավերներին անցնելը։",
    descriptionRu:
      "Более мягкое знакомство с сортировкой цветов: разноцветные деревянные детали нанизаны на один прочный стержень. Ребёнок свободно перемещает, снимает и складывает цвета обратно, расширяя цветовой словарь и укрепляя хват перед переходом к заданиям на подбор узора.",
    priceAmd: 10000,
    category: "educational",
    subcategory: "early-learning",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/rainbow-sorting-board-1-v4.jpg", alt: "Wooden rainbow color sorting board" }],
    inStock: true,
    sku: "58436",
    relatedSlugs: ["color-sorting-board", "counting-frame"],
    dimensions: "21 x 21 x 3.5 cm",
  },
  {
    slug: "wooden-stacking-tower",
    name: "Wobbling Wooden Stacking Tower",
    nameHy: "Տատանվող փայտյա աշտարակ",
    nameRu: "Раскачивающаяся деревянная башня-пирамидка",
    shortDescription: "Seven-piece stacking tower with a rounded base that gently wobbles as it's built.",
    shortDescriptionHy: "Յոթ կտորից բաղկացած աշտարակ՝ կլորացված հիմքով, որը մեղմորեն տատանվում է կառուցելիս։",
    shortDescriptionRu: "Пирамидка из семи деталей с закруглённым основанием, слегка покачивающаяся при сборке.",
    description:
      "Seven graduated wooden rings stack onto a rounded base that rocks gently side to side, turning a simple stacking task into a playful balancing act. Builds eye-hand coordination and an early sense of size and order.",
    descriptionHy:
      "Յոթ աստիճանաբար փոքրացող փայտյա օղակներ դասավորվում են կլորացված հիմքի վրա, որը մեղմորեն օրորվում է կողքից կողք՝ պարզ դասավորման խնդիրը վերածելով խաղային հավասարակշռության վարժանքի։ Զարգացնում է ձեռք-աչք համակարգումը և չափի ու կարգի սկզբնական ընկալումը։",
    descriptionRu:
      "Семь колец разного размера надеваются на закруглённое основание, которое плавно покачивается из стороны в сторону, превращая обычное составление башни в игру на равновесие. Развивает координацию рук и глаз, а также раннее восприятие размера и порядка.",
    priceAmd: 6300,
    category: "wooden-toys",
    subcategory: "stacking-sorting",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-stacking-tower-1.jpg", alt: "Wobbling wooden stacking tower with seven rings" }, { src: "/images/products/wooden-stacking-tower-2.jpg", alt: "Wobbling stacking tower partially disassembled with rings beside it" }],
    inStock: true,
    sku: "58925",
    relatedSlugs: ["stacking-game-zoo", "ball-pyramid-stacking-game"],
    dimensions: "9 x 9 x 12 cm",
  },
  {
    slug: "stacking-game-zoo",
    name: "Stacking Game — Zoo Animals",
    nameHy: "Դասավորման խաղ — Կենդանաբանական այգի",
    nameRu: "Игра-пирамидка «Зоопарк»",
    shortDescription: "Colorful insert-and-stack game featuring friendly zoo animal shapes.",
    shortDescriptionHy: "Գունավոր տեղադրման և դասավորման խաղ՝ ընկերասեր կենդանաբանական այգու կերպարներով։",
    shortDescriptionRu: "Яркая игра на вставление и составление фигур с дружелюбными животными зоопарка.",
    description:
      "Cheerful zoo-animal shapes slide onto a central post in size order, rewarding careful stacking with a stable little tower. Vibrant colors and chunky pieces make this an easy-grip favorite for developing fine motor skills.",
    descriptionHy:
      "Ուրախ կենդանաբանական այգու կերպարները դասավորվում են կենտրոնական ձողի վրա՝ չափերի կարգով, և ուշադիր դասավորումը վարձատրվում է կայուն փոքրիկ աշտարակով։ Վառ գույները և խոշոր կտորները այն դարձնում են հեշտ բռնվող սիրելի խաղալիք՝ նուրբ շարժողական հմտությունների զարգացման համար։",
    descriptionRu:
      "Весёлые фигурки животных зоопарка нанизываются на центральный стержень по размеру, а аккуратная сборка вознаграждается устойчивой башенкой. Яркие цвета и крупные детали делают игрушку удобной для маленьких рук и развивают мелкую моторику.",
    priceAmd: 7300,
    category: "wooden-toys",
    subcategory: "stacking-sorting",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/stacking-game-zoo-1.jpg", alt: "Wooden zoo animal stacking game" }, { src: "/images/products/stacking-game-zoo-2.jpg", alt: "Zoo animal stacking game disassembled showing individual pieces" }, { src: "/images/products/stacking-game-zoo-3.jpg", alt: "Zoo animal stacking game from a side angle" }],
    inStock: true,
    sku: "58356",
    relatedSlugs: ["wooden-stacking-tower", "ball-pyramid-stacking-game"],
    dimensions: "21 x 6 x 12.5 cm",
  },
  {
    slug: "pull-along-surfer-van",
    name: "Pull-Along Surfer Van",
    nameHy: "Հրելով-քաշելով սերֆինգի ֆուրգոն",
    nameRu: "Каталка на верёвочке «Серф-фургон»",
    shortDescription: "Wooden pull-along van with a removable surfboard on top, ready for the beach.",
    shortDescriptionHy: "Փայտյա քաշվող ֆուրգոն՝ վերևում հանվող սերֆինգի տախտակով։",
    shortDescriptionRu: "Деревянный фургончик-каталка со съёмной доской для сёрфинга сверху.",
    description:
      "A cheerful wooden van with a colorful, removable surfboard rides along on a pull-string, giving early walkers a reason to keep moving. Encourages walking confidence, balance, and imaginative beach-day play.",
    descriptionHy:
      "Ուրախ փայտյա ֆուրգոնը՝ գունավոր, հանվող սերֆինգի տախտակով, շարժվում է քաշվող լարով՝ նոր քայլող երեխաներին տալով շարժվելու պատճառ։ Խրախուսում է քայլելու վստահությունը, հավասարակշռությունը և ծովափնյա օրվա երևակայական խաղը։",
    descriptionRu:
      "Весёлый деревянный фургончик с яркой съёмной доской для сёрфинга едет на верёвочке, побуждая малыша, только начавшего ходить, двигаться вперёд. Развивает уверенность в ходьбе, баланс и сюжетную игру «день на пляже».",
    priceAmd: 5200,
    category: "wooden-toys",
    subcategory: "push-pull",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/pull-along-surfer-van-1.jpg", alt: "Wooden pull-along surfer van toy" }, { src: "/images/products/pull-along-surfer-van-2.jpg", alt: "Pull-along surfer van toy from a side angle" }],
    inStock: true,
    sku: "54858",
    relatedSlugs: ["pull-along-rabbit", "push-along-goose"],
    dimensions: "13 x 5.8 x 9.5 cm",
  },
  {
    slug: "pull-along-rabbit",
    name: "Pull-Along Rabbit",
    nameHy: "Հրելով-քաշելով նապաստակ",
    nameRu: "Каталка на верёвочке «Кролик»",
    shortDescription: "Wooden pull-along rabbit with a clover leaf leading the way.",
    shortDescriptionHy: "Փայտյա քաշվող նապաստակ՝ առջևից երեքնուկի տերևով։",
    shortDescriptionRu: "Деревянный кролик-каталка с листочком клевера впереди.",
    description:
      "A cute wooden rabbit trots along behind its clover leaf as your child leads the way on a pull-string. A friendly, up-to-date design that makes new walkers want to keep going.",
    descriptionHy:
      "Հմայիչ փայտյա նապաստակը վազում է իր երեքնուկի տերևի հետևից, երբ Ձեր երեխան ղեկավարում է ճանապարհը քաշվող լարով։ Բարեհամբույր, արդիական դիզայն, որը ցանկություն է առաջացնում նոր քայլող երեխաների մոտ շարունակել շարժվել։",
    descriptionRu:
      "Симпатичный деревянный кролик семенит следом за листочком клевера, пока ребёнок ведёт его на верёвочке. Дружелюбный современный дизайн, который мотивирует малыша, только осваивающего ходьбу, двигаться дальше.",
    priceAmd: 9000,
    category: "wooden-toys",
    subcategory: "push-pull",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/pull-along-rabbit-1.jpg", alt: "Wooden pull-along rabbit toy" }, { src: "/images/products/pull-along-rabbit-2.jpg", alt: "Pull-along rabbit toy, close-up side view" }, { src: "/images/products/pull-along-rabbit-3.jpg", alt: "Pull-along rabbit toy, angled view" }, { src: "/images/products/pull-along-rabbit-4.jpg", alt: "Child playing with the pull-along rabbit toy outdoors" }],
    inStock: true,
    sku: "54897",
    relatedSlugs: ["pull-along-surfer-van", "push-along-goose"],
    dimensions: "15.5 x 8 x 12 cm",
  },
  {
    slug: "push-along-goose",
    name: "Push-Along Goose Bertha",
    nameHy: "Հրելով քայլացվող սագ Բերտա",
    nameRu: "Каталка-гусыня Берта на палочке",
    shortDescription: "Tall push-along goose that walks in step with your toddler.",
    shortDescriptionHy: "Բարձրահասակ հրելով քայլացվող սագ, որը քայլում է Ձեր փոքրիկի հետ քայլ առ քայլ։",
    shortDescriptionRu: "Высокая каталка-гусыня, шагающая в такт с малышом.",
    description:
      "Bertha the goose waddles along in single file with your child, her long handle sized right for standing toddlers. Encourages walking practice and builds the motor skills new walkers need most.",
    descriptionHy:
      "Բերտա սագը կնճռոտվում է շարքով Ձեր երեխայի հետ, նրա երկար բռնակը հարմար չափի է կանգնած փոքրիկների համար։ Խրախուսում է քայլելու վարժանքը և զարգացնում այն շարժողական հմտությունները, որոնք ամենաշատն են անհրաժեշտ նոր քայլող երեխաներին։",
    descriptionRu:
      "Гусыня Берта вперевалку идёт рядом с ребёнком — её длинная ручка подходит именно для стоящих малышей. Помогает отрабатывать ходьбу и развивает моторику, которая больше всего нужна начинающим ходить детям.",
    priceAmd: 12000,
    category: "wooden-toys",
    subcategory: "push-pull",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/push-along-goose-1.jpg", alt: "Wooden push-along goose toy on a long handle" }, { src: "/images/products/push-along-goose-2.jpg", alt: "Push-along goose toy from a side angle" }],
    inStock: true,
    sku: "54860",
    relatedSlugs: ["pull-along-rabbit", "pull-along-surfer-van"],
    dimensions: "25 x 12 x 58 cm",
  },
  {
    slug: "ladder-fire-truck",
    name: "Wooden Ladder Fire Truck",
    nameHy: "Փայտյա սանդուղքով հրշեջ մեքենա",
    nameRu: "Деревянная пожарная машина с лестницей",
    shortDescription: "Sturdy wooden fire truck sized for small hands, with a flexible ladder.",
    shortDescriptionHy: "Ամուր փայտյա հրշեջ մեքենա՝ հարմարեցված փոքրիկ ձեռքերի համար, ճկուն սանդուղքով։",
    shortDescriptionRu: "Прочная деревянная пожарная машина по размеру маленьких рук, с гибкой лестницей.",
    description:
      "A rolling wooden fire truck with a flexible ladder, sized and weighted for the youngest emergency-vehicle fans. Good rolling wheels and rounded edges make this a safe first vehicle toy for the nursery floor.",
    descriptionHy:
      "Անիվավոր փայտյա հրշեջ մեքենա՝ ճկուն սանդուղքով, հարմարեցված ամենափոքր վթարային մեքենաների սիրահարների չափերին ու քաշին։ Լավ գլորվող անիվները և կլորացված եզրերը այն դարձնում են անվտանգ առաջին մեքենա-խաղալիք մանկական սենյակի հատակի համար։",
    descriptionRu:
      "Катящаяся деревянная пожарная машина с гибкой лестницей, подходящая по размеру и весу самым юным поклонникам спецтехники. Хорошо катящиеся колёса и закруглённые края делают её безопасной первой машинкой для игр на полу.",
    priceAmd: 5400,
    category: "wooden-toys",
    subcategory: "push-pull",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/ladder-fire-truck-1.jpg", alt: "Wooden ladder fire truck toy" }, { src: "/images/products/ladder-fire-truck-2.jpg", alt: "Wooden ladder fire truck, close-up angle" }, { src: "/images/products/ladder-fire-truck-3.jpg", alt: "Wooden ladder fire truck, front angle with ladder down" }, { src: "/images/products/ladder-fire-truck-4.jpg", alt: "Wooden ladder fire truck with ladder raised" }],
    inStock: true,
    sku: "55880",
    relatedSlugs: ["push-along-goose", "wooden-car-racetrack"],
    dimensions: "15.5 x 6.5 x 12 cm",
  },
  {
    slug: "wooden-cooking-set",
    name: "Kitchen Love Cooking Set",
    nameHy: "«Խոհանոցի սեր» խոհարարական հավաքածու",
    nameRu: "Набор для готовки «Кухонная любовь»",
    shortDescription: "Five-piece solid beechwood pot, pan, spoon, and spatula set for pretend cooking.",
    shortDescriptionHy: "Հինգ կտորից բաղկացած հաճարենու փայտից ամանեղեն և սպասք՝ երևակայական խոհարարության համար։",
    shortDescriptionRu: "Набор из пяти предметов из массива бука — кастрюля, сковорода, ложка и лопатка для сюжетной игры.",
    description:
      "A sturdy solid-beechwood pot, pan, spoon, and spatula, built to withstand even the most enthusiastic pretend cooking. We leave the menu up to your child's imagination — they'll always find something to whip up.",
    descriptionHy:
      "Ամուր հաճարենու փայտից ամանեղեն և սպասք, կառուցված դիմանալու նույնիսկ ամենակրքոտ երևակայական խոհարարությանը։ Ընտրանացանկը թողնում ենք Ձեր երեխայի երևակայությանը՝ նա միշտ մի բան կգտնի պատրաստելու համար։",
    descriptionRu:
      "Прочная посуда из массива бука — кастрюля, сковорода, ложка и лопатка, — выдерживающая даже самую увлечённую сюжетную готовку. Меню оставляем на усмотрение фантазии вашего ребёнка — он всегда найдёт, что приготовить.",
    priceAmd: 9000,
    category: "wooden-toys",
    subcategory: "pretend-play",
    ageRange: "0-3",
    materials: ["Solid beechwood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-cooking-set-1-v2.jpg", alt: "Wooden cooking set with pot, pan, spoon, and spatula" }, { src: "/images/products/wooden-cooking-set-2.jpg", alt: "Wooden cooking set pieces arranged differently" }, { src: "/images/products/wooden-cooking-set-3.jpg", alt: "Wooden cooking set with pot, pan, and spoon standing upright" }],
    inStock: true,
    sku: "51459",
    featured: true,
    relatedSlugs: ["coffee-tea-station", "wooden-shop-cash-register"],
    dimensions: "17.1 x 12.6 x 7.4 cm",
  },
  {
    slug: "coffee-tea-station",
    name: "Coffee & Tea Play Station",
    nameHy: "Սուրճի և թեյի խաղասեղան",
    nameRu: "Игровая станция «Кофе и чай»",
    shortDescription: "Detailed wooden coffee and tea station with movable parts and lots of accessories.",
    shortDescriptionHy: "Մանրամասն փայտյա սուրճի և թեյի կայան՝ շարժական մասերով և բազմաթիվ պարագաներով։",
    shortDescriptionRu: "Детально проработанная деревянная станция для кофе и чая с подвижными элементами и множеством аксессуаров.",
    description:
      "Built with enough detail that you can almost smell the coffee, this play station comes loaded with accessories and moving parts. Preparing tea and coffee for the whole family becomes an afternoon of pure role-play fun.",
    descriptionHy:
      "Կառուցված այնպիսի մանրամասնությամբ, որ գրեթե կարող եք զգալ սուրճի բույրը, այս խաղասեղանը լցված է պարագաներով և շարժական մասերով։ Ողջ ընտանիքի համար թեյ ու սուրճ պատրաստելը վերածվում է մաքուր դերային խաղի հաճելի կեսօրի։",
    descriptionRu:
      "Станция проработана настолько детально, что можно почти почувствовать аромат кофе — здесь множество аксессуаров и подвижных элементов. Приготовление чая и кофе для всей семьи превращается в настоящую ролевую игру.",
    priceAmd: 15900,
    category: "wooden-toys",
    subcategory: "pretend-play",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/coffee-tea-station-1.jpg", alt: "Wooden coffee and tea play station with accessories" }, { src: "/images/products/coffee-tea-station-2.jpg", alt: "Coffee and tea station from a side angle" }, { src: "/images/products/coffee-tea-station-3.jpg", alt: "Coffee and tea station with accessories arranged in front" }, { src: "/images/products/coffee-tea-station-4.jpg", alt: "Child's hand pressing a button on the coffee and tea station" }, { src: "/images/products/coffee-tea-station-5.jpg", alt: "Coffee and tea station styled on a shelf with play food" }],
    inStock: true,
    sku: "51460",
    relatedSlugs: ["wooden-cooking-set", "wooden-shop-cash-register"],
    dimensions: "18.7 x 12 x 17.5 cm",
  },
  {
    slug: "wooden-shop-cash-register",
    name: "Shop Cash Register with Sound",
    nameHy: "Ձայնով դրամարկղ խանութի համար",
    nameRu: "Игрушечный кассовый аппарат со звуком",
    shortDescription: "Wooden play cash register that pings open, with a chalkboard display and paper roll.",
    shortDescriptionHy: "Փայտյա խաղալիք դրամարկղ, որը բացվում է ձայնով, գրատախտակի էկրանով և թղթի գլանով։",
    shortDescriptionRu: "Игрушечная касса, открывающаяся со звоном, с грифельным дисплеем и рулоном чека.",
    description:
      "This little shopkeeper's register opens with a satisfying ping, presses real buttons, and lets kids chalk up prices on its write-on display. A replaceable paper roll keeps every pretend sale on the record.",
    descriptionHy:
      "Այս փոքրիկ խանութպանի դրամարկղը բացվում է հաճելի ձայնով, ունի սեղմվող կոճակներ և թույլ է տալիս երեխաներին գրել գները իր գրելու համար նախատեսված էկրանին։ Փոխարինվող թղթի գլանը գրանցում է յուրաքանչյուր երևակայական վաճառք։",
    descriptionRu:
      "Кассовый аппарат маленького продавца открывается с приятным звоном, у него нажимаются настоящие кнопки, а на грифельном дисплее можно писать мелом цены. Сменный рулон бумаги фиксирует каждую воображаемую продажу.",
    priceAmd: 19800,
    category: "wooden-toys",
    subcategory: "pretend-play",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-shop-cash-register-1-v3.jpg", alt: "Wooden play cash register with paper roll" }, { src: "/images/products/wooden-shop-cash-register-2.jpg", alt: "Wooden play cash register from a side angle" }, { src: "/images/products/wooden-shop-cash-register-3.jpg", alt: "Wooden play cash register drawer and accessories" }, { src: "/images/products/wooden-shop-cash-register-4.jpg", alt: "Child using the wooden play cash register" }, { src: "/images/products/wooden-shop-cash-register-5.jpg", alt: "Close-up of the wooden play cash register drawer and receipt roll" }],
    inStock: true,
    sku: "51481",
    featured: true,
    relatedSlugs: ["wooden-cooking-set", "coffee-tea-station"],
    dimensions: "19.5 x 23 x 18 cm",
  },
  {
    slug: "hammer-bench",
    name: "Goki Basic Hammer Bench",
    nameHy: "Մուրճով նստարան՝ Goki Basic",
    nameRu: "Стучалка-скамейка Goki Basic",
    shortDescription: "Classic hammer bench angled for a comfortable, satisfying strike every time.",
    shortDescriptionHy: "Դասական մուրճով նստարան՝ հարմար անկյան տակ՝ ամեն անգամ հաճելի հարվածի համար։",
    shortDescriptionRu: "Классическая стучалка с удобным наклоном для приятного и меткого удара каждый раз.",
    description:
      "Five colorful pegs wait to be tapped through the bench with the included wooden mallet, set at an ergonomic angle that makes hammering easier and more satisfying for small arms. A hands-on favorite for cause-and-effect learning.",
    descriptionHy:
      "Հինգ գունավոր սեպեր սպասում են, որ դրանք հարվածեն նստարանով՝ ներառված փայտյա մուրճով, տեղադրված էրգոնոմիկ անկյան տակ, որը հեշտացնում և հաճելի է դարձնում մուրճահարումը փոքրիկ ձեռքերի համար։ Սիրելի ինտերակտիվ խաղալիք՝ պատճառահետևանքային ուսուցման համար։",
    descriptionRu:
      "Пять цветных колышков ждут, чтобы их забили молоточком в скамейку — эргономичный наклон делает удар легче и приятнее для маленьких рук. Любимая интерактивная игрушка для изучения причинно-следственных связей.",
    priceAmd: 8500,
    category: "educational",
    subcategory: "early-learning",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/hammer-bench-1.jpg", alt: "Wooden hammer bench with colorful pegs and mallet" }, { src: "/images/products/hammer-bench-2.jpg", alt: "Child playing with the hammer bench toy" }],
    inStock: true,
    sku: "58581",
    bestseller: true,
    relatedSlugs: ["color-sorting-board", "counting-frame"],
    dimensions: "21 x 8.8 x 8.5 cm",
  },
  {
    slug: "rainbow-xylophone",
    name: "Rainbow Xylophone",
    nameHy: "Ծիածան քսիլոֆոն",
    nameRu: "Радужный ксилофон",
    shortDescription: "Colorfully keyed xylophone for a first taste of making music.",
    shortDescriptionHy: "Գունավոր ստեղներով քսիլոֆոն՝ երաժշտություն ստեղծելու առաջին փորձի համար։",
    shortDescriptionRu: "Ксилофон с цветными пластинками для первого знакомства с музыкой.",
    description:
      "Each bright key rings a clear, true tone, helping little musicians connect color and sound as they experiment with their first melodies. Comes with two mallets sized for small hands.",
    descriptionHy:
      "Յուրաքանչյուր վառ ստեղն հնչում է հստակ, ճշգրիտ տոնով՝ օգնելով փոքրիկ երաժիշտներին կապել գույնը ձայնի հետ, երբ նրանք փորձարկում են իրենց առաջին մեղեդիները։ Գալիս է երկու փոքրիկ ձեռքերի համար հարմարեցված մուրճիկով։",
    descriptionRu:
      "Каждая яркая пластинка звучит чисто и точно, помогая маленьким музыкантам связать цвет со звуком, экспериментируя с первыми мелодиями. В комплекте два молоточка, удобных для маленьких рук.",
    priceAmd: 13800,
    category: "wooden-toys",
    subcategory: "musical",
    ageRange: "3-6",
    materials: ["Wood", "Metal tone bars"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/rainbow-xylophone-1.jpg", alt: "Rainbow-colored wooden xylophone with two mallets" }],
    inStock: true,
    sku: "61979",
    relatedSlugs: ["wooden-drum", "wooden-banjo"],
    dimensions: "31.5 x 16 x 3 cm",
  },
  {
    slug: "wooden-banjo",
    name: "Kids' Wooden Banjo",
    nameHy: "Երեխաների փայտյա բանջո",
    nameRu: "Детское деревянное банджо",
    shortDescription: "Tunable toy banjo with a real sound hole and spare strings included.",
    shortDescriptionHy: "Կարգավորվող խաղալիք բանջո՝ իրական ձայնային անցքով և պահեստային լարերով։",
    shortDescriptionRu: "Настраиваемое игрушечное банджо с настоящим резонаторным отверстием и запасными струнами.",
    description:
      "A colorful, genuinely tunable banjo with a sound hole on the underside for better acoustics, plus a plectrum and spare strings in the box. A fun first introduction to string instruments — more toy than tool, but real enough to strum along to.",
    descriptionHy:
      "Գունավոր, իսկապես կարգավորվող բանջո՝ ներքևում ձայնային անցքով ավելի լավ ակուստիկայի համար, գումարած մատնոց և պահեստային լարեր տուփի մեջ։ Ուրախ առաջին ծանոթություն լարային գործիքների հետ՝ ավելի շուտ խաղալիք, քան գործիք, բայց բավականին իրական՝ նվագելու համար։",
    descriptionRu:
      "Яркое, по-настоящему настраиваемое банджо с резонаторным отверстием снизу для лучшего звучания, плюс медиатор и запасные струны в комплекте. Весёлое первое знакомство со струнными инструментами — скорее игрушка, чем инструмент, но вполне подходящая, чтобы побренчать.",
    priceAmd: 17500,
    category: "wooden-toys",
    subcategory: "musical",
    ageRange: "3-6",
    materials: ["Wood", "Plastic"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-banjo-1.jpg", alt: "Colorful wooden toy banjo" }],
    inStock: true,
    sku: "61870",
    relatedSlugs: ["rainbow-xylophone", "wooden-recorder"],
    dimensions: "52 x 22 x 5.5 cm",
  },
  {
    slug: "wooden-drum",
    name: "Kids' Wooden Drum",
    nameHy: "Երեխաների փայտյա թմբուկ",
    nameRu: "Детский деревянный барабан",
    shortDescription: "Simple, good-sounding wooden drum, tuned to a kid-friendly, moderate volume.",
    shortDescriptionHy: "Պարզ, հաճելի հնչողությամբ փայտյա թմբուկ, կարգավորված չափավոր ձայնի համար։",
    shortDescriptionRu: "Простой, приятно звучащий деревянный барабан умеренной, комфортной для дома громкости.",
    description:
      "Simple, sturdy, and pleasant to listen to — exactly what a child's first drum should be. A great rhythm-keeping companion for family sing-alongs and solo drumming sessions alike.",
    descriptionHy:
      "Պարզ, ամուր և հաճելի լսելի, ճիշտ այն, ինչ պետք է լինի երեխայի առաջին թմբուկը։ Հիանալի ռիթմ պահող ուղեկից՝ ընտանեկան երգելու և միայնակ թմբկահարության համար։",
    descriptionRu:
      "Простой, прочный и приятный на слух — именно таким должен быть первый барабан ребёнка. Отличный спутник для семейных песен и сольных барабанных сессий.",
    priceAmd: 9000,
    category: "wooden-toys",
    subcategory: "musical",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-drum-1.jpg", alt: "Wooden toy drum" }],
    inStock: true,
    sku: "61898",
    relatedSlugs: ["rainbow-xylophone", "wooden-banjo"],
    dimensions: "20.3 x 20.3 x 10 cm",
  },
  {
    slug: "wooden-recorder",
    name: "Wooden Recorder",
    nameHy: "Փայտյա երգեհոն-սրինգ",
    nameRu: "Деревянная блокфлейта",
    shortDescription: "Simple wooden recorder for making music together.",
    shortDescriptionHy: "Պարզ փայտյա սրինգ՝ միասին երաժշտություն ստեղծելու համար։",
    shortDescriptionRu: "Простая деревянная блокфлейта для совместного музицирования.",
    description:
      "A straightforward wooden recorder that trains sensitive listening and fine finger control note by note. Light, easy to hold, and a natural fit alongside our drum and xylophone for a mini family band.",
    descriptionHy:
      "Պարզ փայտյա սրինգ, որը մարզում է լսողության զգայունությունը և մատների նուրբ վերահսկումը՝ ձայն առ ձայն։ Թեթև, հեշտ բռնվող, բնականորեն համադրվում է մեր թմբուկի և քսիլոֆոնի հետ՝ ընտանեկան մինի նվագախումբ ստեղծելու համար։",
    descriptionRu:
      "Простая деревянная блокфлейта, тренирующая чуткость слуха и точность движений пальцев, ноту за нотой. Лёгкая, удобная в руке — отлично сочетается с нашим барабаном и ксилофоном для домашнего мини-оркестра.",
    priceAmd: 4900,
    category: "wooden-toys",
    subcategory: "musical",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-recorder-1.jpg", alt: "Wooden toy recorder" }],
    inStock: true,
    sku: "61921",
    relatedSlugs: ["wooden-drum", "rainbow-xylophone"],
    dimensions: "2.7 x 2.7 x 20 cm",
  },
  {
    slug: "counting-frame",
    name: "Wooden Counting Frame",
    nameHy: "Փայտյա հաշվարկման շրջանակ",
    nameRu: "Деревянные счёты",
    shortDescription: "Classic colorful bead-frame abacus, smooth-running and sturdy.",
    shortDescriptionHy: "Դասական գունավոր հաշվակշիռ-աբակուս՝ սահուն և ամուր։",
    shortDescriptionRu: "Классический цветной абакус на бусинах, плавный и прочный.",
    description:
      "A timeless wooden bead-frame that turns early counting and simple arithmetic into hands-on, colorful practice. Sturdy construction and smooth-sliding beads make it a reliable first math tool.",
    descriptionHy:
      "Ժամանակազերծ փայտյա հաշվակշիռ, որը վաղ հաշվելը և պարզ թվաբանությունը վերածում է ձեռքի, գունավոր վարժանքի։ Ամուր կառուցվածքը և սահուն սահող հաշվակշիռները դարձնում են այն հուսալի առաջին մաթեմատիկական գործիք։",
    descriptionRu:
      "Классические деревянные счёты превращают ранний счёт и простую арифметику в наглядную, цветную практику. Прочная конструкция и плавно скользящие бусины делают их надёжным первым математическим инструментом.",
    priceAmd: 4300,
    category: "educational",
    subcategory: "early-learning",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/counting-frame-1.jpg", alt: "Wooden counting frame abacus" }],
    inStock: true,
    sku: "58518",
    relatedSlugs: ["number-puzzle-0-9", "learn-to-tell-time-set"],
    dimensions: "16 x 4.5 x 18 cm",
  },
  {
    slug: "number-puzzle-0-9",
    name: "Number Puzzle 0–9",
    nameHy: "Թվերի գլուխկոտրուկ 0–9",
    nameRu: "Пазл с цифрами 0–9",
    shortDescription: "Chunky wooden puzzle with numbers 0 through 9 for easy first counting.",
    shortDescriptionHy: "Խոշոր փայտյա գլուխկոտրուկ՝ 0-ից 9 թվերով՝ հեշտ առաջին հաշվելու համար։",
    shortDescriptionRu: "Крупный деревянный пазл с цифрами от 0 до 9 для лёгкого первого счёта.",
    description:
      "Ten chunky number pieces lift out of their tray for tracing, matching, and re-placing, giving little fingers a tactile way to learn to count. A simple, sturdy first step toward number recognition.",
    descriptionHy:
      "Տասը խոշոր թվային կտորներ հանվում են իրենց սկուտեղից՝ հետագծելու, համապատասխանեցնելու և վերադնելու համար՝ փոքրիկ մատներին տալով հպումային ձևով հաշվել սովորելու հնարավորություն։ Պարզ, ամուր առաջին քայլ դեպի թվերի ճանաչում։",
    descriptionRu:
      "Десять крупных цифр вынимаются из лотка для обводки, сопоставления и возврата на место, давая маленьким пальчикам тактильный способ учиться считать. Простой и прочный первый шаг к распознаванию цифр.",
    priceAmd: 4800,
    category: "puzzles-games",
    subcategory: "wooden-puzzles",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/number-puzzle-0-9-1.jpg", alt: "Wooden number puzzle with pieces 0 through 9" }],
    inStock: true,
    sku: "57574",
    relatedSlugs: ["counting-frame", "puzzle-animal-circle"],
    dimensions: "30 x 21 cm",
  },
  {
    slug: "learn-to-tell-time-set",
    name: "Learn to Tell the Time Set",
    nameHy: "«Սովորենք ասել ժամը» հավաքածու",
    nameRu: "Набор «Учимся определять время»",
    shortDescription: "Wooden teaching clock with movable hands and analogue/digital time cards.",
    shortDescriptionHy: "Փայտյա ուսուցողական ժամացույց՝ շարժական սլաքներով և անալոգային/թվային ժամանակի քարտերով։",
    shortDescriptionRu: "Деревянные обучающие часы с подвижными стрелками и карточками аналогового/цифрового времени.",
    description:
      "A wooden clock with a traditional dial and moveable hands, paired with time-template cards showing each hour in both analogue and digital form. A patient, hands-on way to work through the classic hours-and-minutes puzzle.",
    descriptionHy:
      "Փայտյա ժամացույց՝ ավանդական հարթակով և շարժական սլաքներով, զուգակցված ժամանակի նմուշների քարտերով, որոնք ցույց են տալիս յուրաքանչյուր ժամ և՛ անալոգային, և՛ թվային ձևով։ Համբերատար, գործնական միջոց՝ ժամերի ու րոպեների դասական հանելուկը լուծելու համար։",
    descriptionRu:
      "Деревянные часы с классическим циферблатом и подвижными стрелками в паре с карточками-шаблонами, показывающими каждый час в аналоговом и цифровом виде. Терпеливый, наглядный способ разобраться с классической загадкой часов и минут.",
    priceAmd: 6800,
    category: "educational",
    subcategory: "early-learning",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/learn-to-tell-time-set-1.jpg", alt: "Wooden teaching clock with time cards" }, { src: "/images/products/learn-to-tell-time-set-2.jpg", alt: "Close-up of the teaching clock faces and time cards" }],
    inStock: true,
    sku: "58445",
    relatedSlugs: ["counting-frame", "number-puzzle-0-9"],
    dimensions: "12 x 12 x 3.5 cm",
  },
  {
    slug: "color-dice-game",
    name: "Color Dice Game — Geometric Shapes",
    nameHy: "Գունային զառ խաղ — երկրաչափական ձևեր",
    nameRu: "Игра в кости на цвет «Геометрические фигуры»",
    shortDescription: "Roll-and-fill dice game that trains matching colors to complete a picture.",
    shortDescriptionHy: "Նետել-և-լցնել զառային խաղ, որը մարզում է գույների համապատասխանեցումը՝ նկարը լրացնելու համար։",
    shortDescriptionRu: "Игра с кубиком «брось и заполни», развивающая умение подбирать цвета для завершения картинки.",
    description:
      "Roll the dice, find the matching color, and race to complete your picture first. A lively, easy-to-learn game that sharpens color recognition and turn-taking for the whole family table.",
    descriptionHy:
      "Նետեք զառը, գտեք համապատասխան գույնը և մրցեք առաջինը ավարտելու Ձեր նկարը։ Աշխույժ, հեշտ սովորելի խաղ, որը սրում է գույների ճանաչումը և հերթականությամբ խաղալու հմտությունը ողջ ընտանիքի սեղանի շուրջ։",
    descriptionRu:
      "Бросьте кубик, найдите нужный цвет и постарайтесь первым заполнить свою картинку. Живая, простая в освоении игра, оттачивающая распознавание цвета и умение соблюдать очередность за общим столом.",
    priceAmd: 8200,
    category: "puzzles-games",
    subcategory: "first-games",
    ageRange: "0-3",
    materials: ["Wood", "Cardboard"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/color-dice-game-1.jpg", alt: "Color-matching dice game with geometric shapes" }, { src: "/images/products/color-dice-game-2.jpg", alt: "Color dice game town and vehicles scene card" }, { src: "/images/products/color-dice-game-3.jpg", alt: "Color dice game farm and tractor scene card" }, { src: "/images/products/color-dice-game-4.jpg", alt: "Color dice game nature and animals scene card" }, { src: "/images/products/color-dice-game-5.jpg", alt: "Color dice game garden scene card" }],
    inStock: true,
    sku: "56760",
    relatedSlugs: ["ladybird-race-dice-game", "ludo-board-game"],
    dimensions: "17.5 x 17.5 cm",
  },
  {
    slug: "wooden-bead-maze",
    name: "Wooden Bead Maze",
    nameHy: "Փայտյա հաշվակշիռ-լաբիրինթոս",
    nameRu: "Деревянный бисероход-лабиринт",
    shortDescription: "Twisting wire bead maze with three different tracks to explore.",
    shortDescriptionHy: "Ոլորապտույտ մետաղալարով հաշվակշիռ-լաբիրինթոս՝ երեք տարբեր ուղիներով։",
    shortDescriptionRu: "Извилистый бисероход из проволоки с тремя разными траекториями для исследования.",
    description:
      "Three twisting wire tracks send colorful beads sliding, spinning, and clacking under a child's guiding hand. A satisfying, screen-free way to build fine motor control and focus.",
    descriptionHy:
      "Երեք ոլորապտույտ մետաղալար ուղիներ գունավոր հաշվակշիռներին ուղարկում են սահելու, պտտվելու և թխկթխկացնելու երեխայի ուղղորդող ձեռքի ներքո։ Բավարարվածություն պատճառող, էկրանից զերծ ձև՝ նուրբ շարժողական վերահսկումն ու կենտրոնացումը զարգացնելու համար։",
    descriptionRu:
      "Три извилистые проволочные дорожки заставляют цветные бусины скользить, крутиться и постукивать под направляющей рукой ребёнка. Приятный способ без экрана развивать мелкую моторику и концентрацию.",
    priceAmd: 11500,
    category: "educational",
    subcategory: "sensory-play",
    ageRange: "0-3",
    materials: ["Wood", "Metal wire"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-bead-maze-1-v2.jpg", alt: "Wooden bead maze toy with colorful beads" }],
    inStock: true,
    sku: "59982",
    featured: true,
    relatedSlugs: ["touch-lotto-feel-the-shapes", "ball-pyramid-stacking-game"],
    dimensions: "21.8 x 12 x 18 cm",
  },
  {
    slug: "wooden-car-racetrack",
    name: "Wooden Car Racetrack with 3 Cars",
    nameHy: "Փայտյա մեքենաների ուղի՝ 3 մեքենայով",
    nameRu: "Деревянная гоночная трасса с тремя машинками",
    shortDescription: "Gravity-powered wooden racetrack with three wooden cars that loop from top to bottom.",
    shortDescriptionHy: "Ձգողականությամբ աշխատող փայտյա ուղի՝ երեք փայտյա մեքենաներով, որոնք պտտվում են վերևից ներքև։",
    shortDescriptionRu: "Гравитационная деревянная трасса с тремя машинками, которые кружат сверху вниз.",
    description:
      "Set the three wooden cars whizzing along the upper track, watch, listen, and catch each one as it exits below — then send it around again. A cheerful, colorful racetrack that turns cause-and-effect into pure motion-loving fun.",
    descriptionHy:
      "Երեք փայտյա մեքենաները արագ ուղարկեք վերին ուղիով, դիտեք, լսեք և բռնեք յուրաքանչյուրը ներքևից դուրս գալիս, ապա նորից ուղարկեք։ Ուրախ, գունավոր ուղի, որը պատճառահետևանքային կապը վերածում է շարժման հանդեպ մաքուր սիրո։",
    descriptionRu:
      "Запустите три деревянные машинки по верхней трассе, наблюдайте, слушайте и ловите каждую на выходе внизу — а затем отправляйте по новому кругу. Весёлая цветная трасса превращает причинно-следственную связь в чистое удовольствие от движения.",
    priceAmd: 17500,
    category: "educational",
    subcategory: "stem",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-car-racetrack-1.jpg", alt: "Wooden car racetrack with three wooden cars" }, { src: "/images/products/wooden-car-racetrack-2.jpg", alt: "Wooden car racetrack set up on the floor" }, { src: "/images/products/wooden-car-racetrack-3.jpg", alt: "Wooden car racetrack, close-up angle" }],
    inStock: true,
    sku: "53810",
    newArrival: true,
    relatedSlugs: ["ladder-fire-truck", "colorful-building-block-box"],
    dimensions: "30 x 8.5 x 28 cm",
  },
  {
    slug: "colorful-building-block-box",
    name: "Colorful Building Block Box",
    nameHy: "Գունավոր կառուցողական խորանարդիկների արկղ",
    nameRu: "Коробка цветных строительных блоков",
    shortDescription: "Wood-and-cork building block set in bright colors and varied shapes.",
    shortDescriptionHy: "Փայտից և խցանից կառուցողական հավաքածու՝ վառ գույներով և տարբեր ձևերով։",
    shortDescriptionRu: "Набор строительных блоков из дерева и пробки ярких цветов и разных форм.",
    description:
      "Sustainable wood-and-cork blocks in bright colors and playful shapes offer endless building possibilities, from wobbly first towers to elaborate creations. Made from renewable materials that feel as good as they look.",
    descriptionHy:
      "Կայուն փայտից և խցանից բլոկները վառ գույներով և խաղային ձևերով առաջարկում են անվերջ կառուցման հնարավորություններ՝ սկսած սասանվող առաջին աշտարակներից մինչև բարդ ստեղծագործություններ։ Պատրաստված վերականգնվող նյութերից, որոնք զգացվում են նույնքան լավ, որքան երևում են։",
    descriptionRu:
      "Экологичные блоки из дерева и пробки ярких цветов и забавных форм открывают безграничные возможности для строительства — от первых шатких башенок до сложных конструкций. Сделаны из возобновляемых материалов, которые так же приятны на ощупь, как и на вид.",
    priceAmd: 20000,
    category: "educational",
    subcategory: "stem",
    ageRange: "3-6",
    materials: ["Wood", "Cork"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/colorful-building-block-box-1-v2.jpg", alt: "Colorful wood and cork building block set" }, { src: "/images/products/colorful-building-block-box-2.jpg", alt: "Building blocks arranged into a bridge shape" }, { src: "/images/products/colorful-building-block-box-3.jpg", alt: "Building blocks lined up in a row" }, { src: "/images/products/colorful-building-block-box-4.jpg", alt: "Building blocks arranged into an arch shape" }, { src: "/images/products/colorful-building-block-box-5.jpg", alt: "Building blocks arranged into a circular stack" }, { src: "/images/products/colorful-building-block-box-6.jpg", alt: "Building blocks arranged into a tower" }],
    inStock: true,
    sku: "58353",
    featured: true,
    bestseller: true,
    relatedSlugs: ["little-rainbow-building-blocks", "exploration-building-blocks"],
    dimensions: "27.5 x 20.5 x 3.5 cm",
  },
  {
    slug: "little-rainbow-building-blocks",
    name: "Little Rainbow Building Blocks",
    nameHy: "Փոքրիկ ծիածան կառուցողական խորանարդիկներ",
    nameRu: "Маленькие радужные строительные блоки",
    shortDescription: "Maple wood building blocks in harmonious rainbow tones that show off the natural grain.",
    shortDescriptionHy: "Թխկու փայտից կառուցողական խորանարդիկներ՝ ներդաշնակ ծիածանագույն երանգներով, որոնք ցուցադրում են բնական հյուսվածքը։",
    shortDescriptionRu: "Кленовые строительные блоки в гармоничных радужных тонах, подчёркивающих природную текстуру дерева.",
    description:
      "This little rainbow set discovers creative, open-ended play with harmoniously coordinated colors that highlight the natural wood grain rather than covering it up. High-quality maple wood and careful European craftsmanship throughout.",
    descriptionHy:
      "Այս փոքրիկ ծիածան հավաքածուն բացահայտում է ստեղծագործական, բաց խաղը՝ ներդաշնակորեն համադրված գույներով, որոնք ընդգծում են բնական փայտի հյուսվածքը, այլ ոչ թե ծածկում այն։ Բարձրորակ թխկու փայտ և ուշադիր եվրոպական վարպետություն ողջ ընթացքում։",
    descriptionRu:
      "Этот маленький радужный набор открывает свободную творческую игру с гармонично подобранными цветами, которые подчёркивают натуральную текстуру дерева, а не скрывают её. Высококачественный клён и тщательное европейское мастерство исполнения.",
    priceAmd: 11800,
    category: "wooden-toys",
    subcategory: "stacking-sorting",
    ageRange: "0-3",
    materials: ["Maple wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/little-rainbow-building-blocks-1.jpg", alt: "Rainbow-toned maple wood building blocks" }, { src: "/images/products/little-rainbow-building-blocks-2.jpg", alt: "Rainbow building blocks stacked into an arch" }, { src: "/images/products/little-rainbow-building-blocks-3.jpg", alt: "Rainbow building blocks arranged in a spiral" }, { src: "/images/products/little-rainbow-building-blocks-4.jpg", alt: "Rainbow building blocks arranged into a curved shape" }, { src: "/images/products/little-rainbow-building-blocks-5.jpg", alt: "Rainbow building blocks styled with a small illustrated landscape" }, { src: "/images/products/little-rainbow-building-blocks-6.jpg", alt: "Rainbow building blocks stacked into a classic arch" }],
    inStock: true,
    sku: "58479",
    relatedSlugs: ["colorful-building-block-box", "wooden-stacking-tower"],
    dimensions: "19 x 6 x 9.5 cm",
  },
  {
    slug: "touch-lotto-feel-the-shapes",
    name: "Touch Lotto — Feel the Shapes",
    nameHy: "Հպումային լոտո — Զգա ձևերը",
    nameRu: "Тактильное лото «Почувствуй форму»",
    shortDescription: "Touch-based memory game where hidden shapes are matched by feel alone.",
    shortDescriptionHy: "Հպումային հիշողության խաղ, որտեղ թաքնված ձևերը համապատասխանեցվում են միայն շոշափելով։",
    shortDescriptionRu: "Тактильная игра на память, где спрятанные фигуры находят на ощупь.",
    description:
      "Sixteen picture pairs turn the classic memory game on its head — one card is visible, its match is hidden in a fabric bag and must be found by touch alone. Sturdy wood and durable fabric make this a favorite pre-school sensory game.",
    descriptionHy:
      "Տասնվեց նկարային զույգեր դասական հիշողության խաղը շրջում են գլխիվայր. մեկ քարտ տեսանելի է, նրա զույգը թաքնված է կտավե պարկի մեջ և պետք է գտնվի միայն շոշափելով։ Ամուր փայտը և դիմացկուն կտավը այն դարձնում են սիրելի նախադպրոցական զգայական խաղ։",
    descriptionRu:
      "Шестнадцать пар картинок переворачивают классическую игру на память: одна карточка видна, а её пара спрятана в тканевом мешочке и находится только на ощупь. Прочное дерево и износостойкая ткань делают игру любимой сенсорной игрой дошкольников.",
    priceAmd: 12000,
    category: "educational",
    subcategory: "sensory-play",
    ageRange: "3-6",
    materials: ["Wood", "Fabric"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/touch-lotto-feel-the-shapes-1.jpg", alt: "Touch lotto sensory memory game" }, { src: "/images/products/touch-lotto-feel-the-shapes-2.jpg", alt: "Child reaching into a felt bag to feel a shape" }, { src: "/images/products/touch-lotto-feel-the-shapes-3.jpg", alt: "Touch lotto matching card with fruit shapes" }, { src: "/images/products/touch-lotto-feel-the-shapes-4.jpg", alt: "Touch lotto matching card with vehicle shapes" }, { src: "/images/products/touch-lotto-feel-the-shapes-5.jpg", alt: "Touch lotto matching card with rainbow and cloud shapes" }, { src: "/images/products/touch-lotto-feel-the-shapes-6.jpg", alt: "Touch lotto matching card with insect shapes" }, { src: "/images/products/touch-lotto-feel-the-shapes-7.jpg", alt: "Touch lotto matching card with nature shapes" }],
    inStock: true,
    sku: "59972",
    relatedSlugs: ["wooden-bead-maze", "feel-a-pair-memo"],
    dimensions: "17.5 x 17.5 cm",
  },
  {
    slug: "ball-pyramid-stacking-game",
    name: "Ball Pyramid Stacking Game",
    nameHy: "Գնդիկների բուրգի դասավորման խաղ",
    nameRu: "Игра-пирамидка из шариков",
    shortDescription: "Fourteen colorful wooden balls to sort by color, stack, and roll.",
    shortDescriptionHy: "Տասնչորս գունավոր փայտյա գնդիկներ՝ գույնով տեսակավորելու, դասավորելու և գլորելու համար։",
    shortDescriptionRu: "Четырнадцать цветных деревянных шариков — сортировать по цвету, складывать и катать.",
    description:
      "Fourteen colorful wooden balls stack into a clear, satisfying pyramid, with nine of them sorting by color onto their own base plate. Stimulates visual perception and hand-eye coordination, and invites cooperative play between siblings and friends.",
    descriptionHy:
      "Տասնչորս գունավոր փայտյա գնդիկներ դասավորվում են հստակ, բավարարվածություն պատճառող բուրգի մեջ, որոնցից ինը տեսակավորվում են գույնով իրենց հիմքի վրա։ Խթանում է տեսողական ընկալումը և ձեռք-աչք համակարգումը, և հրավիրում է քույր-եղբայրների ու ընկերների համագործակցային խաղին։",
    descriptionRu:
      "Четырнадцать цветных деревянных шариков складываются в чёткую, приятную глазу пирамиду, причём девять из них сортируются по цвету на отдельной подставке. Развивает зрительное восприятие и координацию рук и глаз, приглашает к совместной игре с братьями, сёстрами и друзьями.",
    priceAmd: 9400,
    category: "wooden-toys",
    subcategory: "stacking-sorting",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/ball-pyramid-stacking-game-1.jpg", alt: "Wooden ball pyramid stacking and sorting game" }, { src: "/images/products/ball-pyramid-stacking-game-2.jpg", alt: "Ball pyramid game with a different hole-pattern board" }, { src: "/images/products/ball-pyramid-stacking-game-3.jpg", alt: "Ball pyramid stacking game, balls arranged differently" }, { src: "/images/products/ball-pyramid-stacking-game-4.jpg", alt: "Ball pyramid stacking game with balls grouped by color" }, { src: "/images/products/ball-pyramid-stacking-game-5.jpg", alt: "Ball pyramid stacking game with white balls set aside" }, { src: "/images/products/ball-pyramid-stacking-game-6.jpg", alt: "Child placing a ball into the stacking game" }, { src: "/images/products/ball-pyramid-stacking-game-7.jpg", alt: "Ball pyramid stacking game, step-by-step arrangement guide" }],
    inStock: true,
    sku: "58335",
    relatedSlugs: ["wooden-stacking-tower", "stacking-game-zoo"],
    dimensions: "15 x 15 x 11 cm",
  },
  {
    slug: "puzzle-life-on-the-farm",
    name: "Puzzle — Life on the Farm",
    nameHy: "Գլուխկոտրուկ — Կյանքն ագարակում",
    nameRu: "Пазл «Жизнь на ферме»",
    shortDescription: "48-piece wooden puzzle depicting a warm farmyard scene.",
    shortDescriptionHy: "48 կտորից բաղկացած փայտյա գլուխկոտրուկ՝ ագարակի ջերմ տեսարանով։",
    shortDescriptionRu: "Деревянный пазл из 48 деталей с тёплой сценкой из жизни фермы.",
    description:
      "Forty-eight sturdy wooden pieces build up into a heartwarming mother-and-child farmyard scene, giving young puzzlers a satisfying, screen-free challenge. Thick pieces are easy to grip and hard to lose.",
    descriptionHy:
      "Քառասունութ ամուր փայտյա կտորներ կազմում են սրտառուչ մայր-երեխա ագարակային տեսարան՝ երիտասարդ գլուխկոտրուկագործներին տալով բավարարվածություն պատճառող, էկրանից զերծ մարտահրավեր։ Հաստ կտորները հեշտ է բռնել և դժվար է կորցնել։",
    descriptionRu:
      "Сорок восемь прочных деревянных деталей складываются в трогательную сценку «мать и дитя» на ферме, предлагая юным собирателям пазлов увлекательное занятие без экрана. Толстые детали удобно держать и трудно потерять.",
    priceAmd: 5600,
    category: "puzzles-games",
    subcategory: "wooden-puzzles",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/puzzle-life-on-the-farm-1.jpg", alt: "Wooden farm scene puzzle" }],
    inStock: true,
    sku: "57745",
    relatedSlugs: ["puzzle-riding-stable", "puzzle-noahs-ark"],
    dimensions: "40 x 30 cm",
  },
  {
    slug: "puzzle-noahs-ark",
    name: "Puzzle — Noah's Ark",
    nameHy: "Գլուխկոտրուկ — Նոյյան տապան",
    nameRu: "Пазл «Ноев ковчег»",
    shortDescription: "96-piece wooden puzzle revealing the ark and its animals.",
    shortDescriptionHy: "96 կտորից բաղկացած փայտյա գլուխկոտրուկ՝ բացահայտում է տապանն ու նրա կենդանիներին։",
    shortDescriptionRu: "Деревянный пазл из 96 деталей с изображением ковчега и его обитателей.",
    description:
      "Ninety-six pieces reveal a colorful ark scene crowded with pairs of animals, rewarding patience and persistence one piece at a time. A satisfying step up for puzzlers ready for more of a challenge.",
    descriptionHy:
      "Իննսունվեց կտոր բացահայտում են գունավոր տապանի տեսարան՝ լեցուն կենդանիների զույգերով, պարգևատրելով համբերությունն ու հետևողականությունը՝ կտոր առ կտոր։ Բավարարվածություն պատճառող առաջընթաց այն երեխաների համար, ովքեր պատրաստ են ավելի մեծ մարտահրավերի։",
    descriptionRu:
      "Девяносто шесть деталей раскрывают яркую сценку с ковчегом, полным пар животных, вознаграждая терпение и настойчивость с каждой деталью. Приятный шаг вперёд для тех, кто готов к более серьёзному вызову.",
    priceAmd: 5600,
    category: "puzzles-games",
    subcategory: "wooden-puzzles",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/puzzle-noahs-ark-1.jpg", alt: "Wooden Noah's Ark puzzle" }],
    inStock: true,
    sku: "57535",
    relatedSlugs: ["puzzle-life-on-the-farm", "puzzle-riding-stable"],
    dimensions: "40 x 30 cm",
  },
  {
    slug: "puzzle-animal-circle",
    name: "Puzzle — Animal Circle",
    nameHy: "Գլուխկոտրուկ — Կենդանիների շրջան",
    nameRu: "Пазл «Круг животных»",
    shortDescription: "27-piece round wooden puzzle with animals circling their king.",
    shortDescriptionHy: "27 կտորից բաղկացած կլոր փայտյա գլուխկոտրուկ՝ իրենց թագավորի շուրջը կանգնած կենդանիներով։",
    shortDescriptionRu: "Круглый деревянный пазл из 27 деталей с животными вокруг своего короля.",
    description:
      "One animal follows another in a friendly circle, with the animal king taking his place at the center. A satisfying round format that's a fresh change from the usual rectangular puzzle tray.",
    descriptionHy:
      "Մի կենդանին հետևում է մյուսին բարեկամական շրջանում, իսկ կենդանիների թագավորը զբաղեցնում է իր տեղը կենտրոնում։ Բավարարվածություն պատճառող կլոր ձևաչափ, որը թարմ փոփոխություն է սովորական ուղղանկյուն սկուտեղից։",
    descriptionRu:
      "Одно животное следует за другим в дружелюбном круге, а звериный король занимает своё место в центре. Приятный круглый формат — свежая перемена по сравнению с обычным прямоугольным лотком.",
    priceAmd: 4800,
    category: "puzzles-games",
    subcategory: "wooden-puzzles",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/puzzle-animal-circle-1.jpg", alt: "Round wooden animal circle puzzle" }],
    inStock: true,
    sku: "57790",
    relatedSlugs: ["number-puzzle-0-9", "puzzle-life-on-the-farm"],
    dimensions: "30.5 x 30.5 cm",
  },
  {
    slug: "puzzle-riding-stable",
    name: "Puzzle — Riding Stable",
    nameHy: "Գլուխկոտրուկ — Ձիարշավային ախոռ",
    nameRu: "Пазл «Конная школа»",
    shortDescription: "96-piece wooden puzzle revealing a lively riding stable scene.",
    shortDescriptionHy: "96 կտորից բաղկացած փայտյա գլուխկոտրուկ՝ բացահայտում է աշխույժ ձիարշավային ախոռի տեսարան։",
    shortDescriptionRu: "Деревянный пазл из 96 деталей, раскрывающий оживлённую сценку конной школы.",
    description:
      "Piece together ninety-six chunky wooden pieces to reveal a bustling riding stable full of horses and riders. A favorite for animal lovers working their way up to bigger puzzles.",
    descriptionHy:
      "Հավաքեք իննսունվեց հաստ փայտյա կտորները՝ բացահայտելու համար եռուզեռով լի ձիարշավային ախոռ՝ լի ձիերով ու հեծյալներով։ Սիրելի ընտրություն կենդանիների սիրահարների համար, ովքեր զարգանում են ավելի մեծ գլուխկոտրուկների ուղղությամբ։",
    descriptionRu:
      "Соберите девяносто шесть крупных деревянных деталей, чтобы открыть оживлённую сценку конной школы с лошадьми и наездниками. Любимец детей, увлечённых животными и готовых к пазлам покрупнее.",
    priceAmd: 5600,
    category: "puzzles-games",
    subcategory: "wooden-puzzles",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/puzzle-riding-stable-1.jpg", alt: "Wooden riding stable puzzle" }],
    inStock: true,
    sku: "57367",
    relatedSlugs: ["puzzle-noahs-ark", "puzzle-life-on-the-farm"],
    dimensions: "40 x 30 cm",
  },
  {
    slug: "domino-game-ladybirds",
    name: "Domino Game — Ladybirds",
    nameHy: "Դոմինո խաղ — Զատիկներ",
    nameRu: "Домино «Божьи коровки»",
    shortDescription: "Classic wooden domino set counted out in ladybird spots instead of pips.",
    shortDescriptionHy: "Դասական փայտյա դոմինոյի հավաքածու՝ հաշվված զատիկների բծերով՝ սովորական կետերի փոխարեն։",
    shortDescriptionRu: "Классическое деревянное домино, где вместо точек — пятнышки на божьих коровках.",
    description:
      "Each wooden domino carries a different number of charming ladybird spots, joined the classic way — matching quantity to quantity. Builds an intuitive feel for numbers and quantity while playing a beloved family game.",
    descriptionHy:
      "Յուրաքանչյուր փայտյա դոմինո կրում է հմայիչ զատիկների տարբեր քանակությամբ բծեր, միացվում է դասական ձևով՝ քանակը քանակին համապատասխանեցնելով։ Զարգացնում է թվերի և քանակների ինտուիտիվ ընկալումը՝ խաղալով սիրելի ընտանեկան խաղը։",
    descriptionRu:
      "На каждой деревянной костяшке — своё число очаровательных пятнышек божьей коровки, а соединяются они классическим способом — количество к количеству. Развивает интуитивное чувство числа и количества за любимой семейной игрой.",
    priceAmd: 4800,
    category: "puzzles-games",
    subcategory: "matching-memory",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/domino-game-ladybirds-1-v2.jpg", alt: "Wooden ladybird domino game" }],
    inStock: true,
    sku: "56716",
    relatedSlugs: ["ladybird-race-dice-game", "feel-a-pair-memo"],
    dimensions: "22.5 x 7.4 x 3.2 cm",
  },
  {
    slug: "feel-a-pair-memo",
    name: "Feel-a-Pair Memo Game",
    nameHy: "«Զգա զույգը» հիշողության խաղ",
    nameRu: "Игра на память «Найди пару на ощупь»",
    shortDescription: "Touch-based matching game — find the identical surface by feel alone.",
    shortDescriptionHy: "Հպումային համապատասխանեցման խաղ — գտիր նույնական մակերևույթը միայն շոշափելով։",
    shortDescriptionRu: "Тактильная игра на сопоставление — найди одинаковую поверхность только на ощупь.",
    description:
      "Run your fingers over each textured tile to find its identical match, training a kind of perception that screens simply can't reach. A calm, focused game that rewards patience and a careful touch.",
    descriptionHy:
      "Անցկացրեք մատները յուրաքանչյուր հյուսվածքային սալիկի վրայով՝ գտնելու համար նրա նույնական զույգը՝ մարզելով մի տեսակ ընկալում, որին էկրանները պարզապես չեն կարող հասնել։ Հանգիստ, կենտրոնացած խաղ, որը վարձատրում է համբերությունն ու ուշադիր հպումը։",
    descriptionRu:
      "Проведите пальцами по каждой текстурной плитке, чтобы найти её идентичную пару, тренируя восприятие, до которого экранам просто не дотянуться. Спокойная, сосредоточенная игра, вознаграждающая терпение и внимательное прикосновение.",
    priceAmd: 12300,
    category: "puzzles-games",
    subcategory: "matching-memory",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/feel-a-pair-memo-1.jpg", alt: "Feel-a-pair textured memory matching game" }],
    inStock: true,
    sku: "56895",
    relatedSlugs: ["surface-feel-memo", "touch-lotto-feel-the-shapes"],
    dimensions: "27.5 x 12.5 x 3.6 cm",
  },
  {
    slug: "surface-feel-memo",
    name: "Surface Feel-Memo Game",
    nameHy: "Մակերևույթի հպումային հիշողության խաղ",
    nameRu: "Игра на память «Текстуры на ощупь»",
    shortDescription: "32-piece wooden memory game matched entirely by touch and texture.",
    shortDescriptionHy: "32 կտորից բաղկացած փայտյա հիշողության խաղ, որը լիովին համապատասխանեցվում է հպումով ու հյուսվածքով։",
    shortDescriptionRu: "Деревянная игра на память из 32 деталей, где пары находят исключительно на ощупь.",
    description:
      "Thirty-two wooden pieces hide their texture until fingers find two that feel exactly alike — only then do players flip them over to check. A different, quieter kind of memory game that sharpens perceptive touch.",
    descriptionHy:
      "Երեսուներկու փայտյա կտորներ թաքցնում են իրենց հյուսվածքը, մինչև մատները չգտնեն երկուսը, որոնք ճիշտ նույն կերպ են զգացվում, և միայն այդ ժամանակ խաղացողները շրջում են դրանք ստուգելու համար։ Հիշողության խաղի այլ, ավելի հանգիստ տեսակ, որը սրում է ընկալունակ հպումը։",
    descriptionRu:
      "Тридцать две деревянные детали скрывают свою текстуру, пока пальцы не найдут две абсолютно одинаковые на ощупь — только тогда игроки переворачивают их для проверки. Другой, более спокойный вид игры на память, оттачивающий чуткость осязания.",
    priceAmd: 19000,
    category: "puzzles-games",
    subcategory: "matching-memory",
    ageRange: "3-6",
    materials: ["Wood", "Fabric"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/surface-feel-memo-1.jpg", alt: "Surface texture feel memory game" }],
    inStock: true,
    sku: "59004",
    relatedSlugs: ["feel-a-pair-memo", "touch-lotto-feel-the-shapes"],
    dimensions: "17 x 17 x 8 cm",
  },
  {
    slug: "ludo-board-game",
    name: "Classic Ludo Board Game",
    nameHy: "Դասական «Լուդո» սեղանի խաղ",
    nameRu: "Классическая настольная игра «Людо»",
    shortDescription: "Wooden ludo set with a clever board that adapts to the number of players.",
    shortDescriptionHy: "Փայտյա «Լուդո» հավաքածու՝ խորամանկ տախտակով, որը հարմարվում է խաղացողների քանակին։",
    shortDescriptionRu: "Деревянный набор «Людо» с хитрой доской, подстраивающейся под число игроков.",
    description:
      "A beloved classic dice game with a clever twist — the board itself can be reconfigured to suit however many players show up to play. Simple rules make it a reliable go-to for family game night.",
    descriptionHy:
      "Սիրված դասական զառային խաղ՝ խորամանկ շրջադարձով. տախտակը ինքնին կարող է վերակազմավորվել՝ հարմարվելու համար այն ամենին, թե որքան խաղացող է գալիս խաղալու։ Պարզ կանոնները այն դարձնում են հուսալի ընտրություն ընտանեկան խաղի երեկոյի համար։",
    descriptionRu:
      "Любимая классическая игра в кости с хитрой особенностью — саму доску можно перестроить под любое число игроков. Простые правила делают её надёжным выбором для семейного игрового вечера.",
    priceAmd: 15500,
    category: "puzzles-games",
    subcategory: "first-games",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/ludo-board-game-1.jpg", alt: "Wooden ludo board game" }],
    inStock: true,
    sku: "56914",
    relatedSlugs: ["color-dice-game", "ladybird-race-dice-game"],
    dimensions: "24 x 24 cm",
  },
  {
    slug: "guess-who-i-am-game",
    name: "Guess Who I Am?",
    nameHy: "«Կռահիր, ով եմ ես» խաղ",
    nameRu: "Игра «Угадай, кто я?»",
    shortDescription: "Classic guessing game that teaches kids to describe and deduce.",
    shortDescriptionHy: "Դասական կռահման խաղ, որը երեխաներին սովորեցնում է նկարագրել ու եզրակացնել։",
    shortDescriptionRu: "Классическая игра-угадайка, учащая детей описывать и делать выводы.",
    description:
      "Players take turns asking clever questions to figure out who — or what — their opponent is thinking of. A wonderful way to teach kids to notice features, describe them precisely, and reason their way to an answer.",
    descriptionHy:
      "Խաղացողները հերթով խորամանկ հարցեր են տալիս՝ պարզելու համար, թե ով կամ ինչ է իրենց հակառակորդը մտածում։ Հրաշալի միջոց՝ երեխաներին սովորեցնելու նկատել առանձնահատկությունները, ճշգրիտ նկարագրել դրանք և տրամաբանորեն հասնել պատասխանի։",
    descriptionRu:
      "Игроки по очереди задают хитрые вопросы, чтобы угадать, кого или что задумал соперник. Прекрасный способ научить детей замечать особенности, точно их описывать и логически приходить к ответу.",
    priceAmd: 9800,
    category: "puzzles-games",
    subcategory: "first-games",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/guess-who-i-am-game-1.jpg", alt: "Guess Who I Am wooden guessing game" }, { src: "/images/products/guess-who-i-am-game-2.jpg", alt: "Guess Who I Am game cards in their wooden stand" }, { src: "/images/products/guess-who-i-am-game-3.jpg", alt: "Two Guess Who I Am game stands side by side" }],
    inStock: true,
    sku: "56311",
    relatedSlugs: ["ludo-board-game", "domino-game-ladybirds"],
    dimensions: "20 x 30 cm",
  },
  {
    slug: "ladybird-race-dice-game",
    name: "Ladybird Race Dice Game",
    nameHy: "«Զատիկների մրցավազք» զառային խաղ",
    nameRu: "Игра в кости «Гонка божьих коровок»",
    shortDescription: "Colorful dice race where players advance their ladybird toward the finish line.",
    shortDescriptionHy: "Գունավոր զառային մրցավազք, որտեղ խաղացողները առաջ են տանում իրենց զատիկը դեպի ֆինիշ։",
    shortDescriptionRu: "Яркая гонка на кубиках, где игроки продвигают свою божью коровку к финишу.",
    description:
      "All ladybirds to the start — the race begins! A roll of the dice decides who advances, teaching colors playfully as the first to the finish line wins. A perfect first competitive game for little explorers.",
    descriptionHy:
      "Բոլոր զատիկները մեկնարկային գծի մոտ․ մրցավազքը սկսվում է։ Զառի նետումը որոշում է, թե ով է առաջ գնում, խաղալիորեն սովորեցնելով գույները, մինչև ֆինիշին առաջինը հասնողը հաղթում է։ Կատարյալ առաջին մրցակցային խաղ փոքրիկ ուսումնասիրողների համար։",
    descriptionRu:
      "Все божьи коровки на старт — гонка начинается! Бросок кубика решает, кто продвигается вперёд, попутно играючи знакомя с цветами, а победителем становится тот, кто первым доберётся до финиша. Отличная первая соревновательная игра для маленьких исследователей.",
    priceAmd: 7200,
    category: "puzzles-games",
    subcategory: "first-games",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/ladybird-race-dice-game-1.jpg", alt: "Ladybird race dice board game" }, { src: "/images/products/ladybird-race-dice-game-2-v2.jpg", alt: "Ladybird race dice game, close-up of the board" }, { src: "/images/products/ladybird-race-dice-game-3-v2.jpg", alt: "Ladybird race dice game pieces and dice" }],
    inStock: true,
    sku: "56319",
    relatedSlugs: ["color-dice-game", "domino-game-ladybirds"],
    dimensions: "54 x 11 x 3.5 cm",
  },
  {
    slug: "rocking-motorcycle",
    name: "Wooden Rocking Motorcycle",
    nameHy: "Փայտյա օրորվող մոտոցիկլետ",
    nameRu: "Деревянный качалка-мотоцикл",
    shortDescription: "Expertly crafted wooden rocking motorcycle for backyard summer road trips.",
    shortDescriptionHy: "Վարպետորեն մշակված փայտյա օրորվող մոտոցիկլետ՝ բակի ամառային ճամփորդությունների համար։",
    shortDescriptionRu: "Искусно изготовленный деревянный мотоцикл-качалка для летних «поездок» на заднем дворе.",
    description:
      "Climb on and start swinging — the nursery becomes a summer country road. This attractive, child-friendly model made of expertly crafted wood needs no assembly skills from grown-ups: it's all about swinging fun, with a 32 cm seat height.",
    descriptionHy:
      "Բարձրացեք և սկսեք օրորվել․ մանկական սենյակը դառնում է ամառային գյուղական ճանապարհ։ Այս գրավիչ, երեխայի համար հարմար մոդելը՝ վարպետորեն մշակված փայտից, մեծերից հավաքման հմտություններ չի պահանջում․ ամեն ինչ օրորվելու հաճույքի մասին է, 32 սմ նստատեղի բարձրությամբ։",
    descriptionRu:
      "Забирайтесь и начинайте качаться — детская превращается в летнюю просёлочную дорогу. Эта привлекательная, дружелюбная к ребёнку модель из искусно обработанного дерева не требует навыков сборки от взрослых: всё дело в удовольствии от качания, высота сиденья — 32 см.",
    priceAmd: 38000,
    category: "outdoor-play",
    subcategory: "ride-on",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/rocking-motorcycle-1-v2.jpg", alt: "Wooden rocking motorcycle toy" }],
    inStock: true,
    sku: "53837",
    featured: true,
    relatedSlugs: ["wooden-rocking-horse", "ride-on-vehicle-blue"],
    dimensions: "78 x 30.5 x 52 cm",
  },
  {
    slug: "wooden-rocking-horse",
    name: "Classic Wooden Rocking Horse",
    nameHy: "Դասական փայտյա օրորվող ձի",
    nameRu: "Классическая деревянная лошадка-качалка",
    shortDescription: "Elegant Scandinavian-style rocking horse crafted from solid natural wood.",
    shortDescriptionHy: "Նրբագեղ սկանդինավյան ոճի օրորվող ձի՝ պատրաստված զանգվածեղեն բնական փայտից։",
    shortDescriptionRu: "Изящная лошадка-качалка в скандинавском стиле из массива натурального дерева.",
    description:
      "Refined, simple, and built for everyday use, this beautiful rocking horse in natural wood was made for one purpose: children want to ride, and ride they will. Side pieces and a backrest keep the seat secure at a 30 cm seat height.",
    descriptionHy:
      "Նրբագեղ, պարզ և կառուցված ամենօրյա օգտագործման համար, այս գեղեցիկ օրորվող ձին բնական փայտից պատրաստված է մեկ նպատակի համար. երեխաները ցանկանում են հեծնել, և նրանք կհեծնեն։ Կողային մասերն ու մեջքի հենարանը ապահով են պահում նստատեղը՝ 30 սմ բարձրությամբ։",
    descriptionRu:
      "Изящная, простая и созданная для ежедневного использования, эта красивая лошадка-качалка из натурального дерева служит одной цели: дети хотят кататься — и будут. Боковые части и спинка надёжно удерживают сиденье на высоте 30 см.",
    priceAmd: 39500,
    category: "outdoor-play",
    subcategory: "ride-on",
    ageRange: "0-3",
    materials: ["Wood", "Metal"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/wooden-rocking-horse-1-v2.jpg", alt: "Classic wooden rocking horse" }, { src: "/images/products/wooden-rocking-horse-2.jpg", alt: "Classic wooden rocking horse, side angle" }],
    inStock: true,
    sku: "53933",
    featured: true,
    bestseller: true,
    relatedSlugs: ["rocking-motorcycle", "ride-on-vehicle-blue"],
    dimensions: "78 x 30.5 x 57 cm",
  },
  {
    slug: "ride-on-vehicle-blue",
    name: "Ride-On Vehicle, Blue",
    nameHy: "Հեծանվարկվող մեքենա, կապույտ",
    nameRu: "Машинка-каталка, синяя",
    shortDescription: "High-quality metal ride-on car with rubber tires for little racers.",
    shortDescriptionHy: "Բարձրորակ մետաղական հեծանվարկվող մեքենա՝ ռետինե անվադողերով փոքրիկ մրցարշավորդների համար։",
    shortDescriptionRu: "Качественная металлическая машинка-каталка на резиновых колёсах для маленьких гонщиков.",
    description:
      "A sturdy metal-and-plastic ride-on with real rubber tires, built to handle a determined toddler's need for speed. Rolls smoothly across floors and pavement, developing leg strength and motor skills with every push.",
    descriptionHy:
      "Ամուր մետաղից ու պլաստիկից հեծանվարկվող մեքենա՝ իրական ռետինե անվադողերով, կառուցված դիմանալու վճռական փոքրիկի արագության կարիքին։ Սահուն գլորվում է հատակների ու մայթերի վրայով՝ զարգացնելով ոտքերի ուժն ու շարժողական հմտությունները յուրաքանչյուր հրումով։",
    descriptionRu:
      "Прочная машинка-каталка из металла и пластика на настоящих резиновых колёсах, готовая выдержать потребность решительного малыша в скорости. Плавно катится по полу и асфальту, развивая силу ног и моторику с каждым толчком.",
    priceAmd: 69000,
    category: "outdoor-play",
    subcategory: "ride-on",
    ageRange: "0-3",
    materials: ["Metal", "Plastic"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/ride-on-vehicle-blue-1.jpg", alt: "Blue metal ride-on toy car" }],
    inStock: true,
    sku: "14166",
    relatedSlugs: ["rocking-motorcycle", "wooden-rocking-horse"],
    dimensions: "73.5 x 35 x 40 cm",
  },
  {
    slug: "hoopla-ring-toss-game",
    name: "Hoopla Ring Toss with 6 Sisal Rings",
    nameHy: "«Հուպլա» օղակների նետման խաղ՝ 6 սիզալային օղակով",
    nameRu: "Игра в кольца «Хупла» с 6 сизалевыми кольцами",
    shortDescription: "Family-friendly ring toss game made in Germany with six sisal rings.",
    shortDescriptionHy: "Ընտանեկան «Հուպլա» խաղ՝ Գերմանիայում պատրաստված, վեց սիզալային օղակով։",
    shortDescriptionRu: "Семейная игра в кольца, изготовленная в Германии, с шестью сизалевыми кольцами.",
    description:
      "Skill, a good eye, and a little luck are all this classic ring toss game needs — and it can be played again and again, anywhere. Clear, functional design and sturdy craftsmanship built for years of backyard tournaments.",
    descriptionHy:
      "Հմտություն, լավ աչք և մի փոքր բախտ. սա այն ամենն է, ինչ պետք է այս դասական օղակների նետման խաղին, և այն կարելի է խաղալ կրկին ու կրկին, ցանկացած տեղում։ Հստակ, ֆունկցիոնալ դիզայն և ամուր վարպետություն՝ բակի տարիների մրցաշարերի համար։",
    descriptionRu:
      "Ловкость, меткий глаз и немного удачи — вот всё, что нужно для этой классической игры в кольца, в которую можно играть снова и снова где угодно. Чёткий, функциональный дизайн и прочное исполнение — на долгие годы турниров во дворе.",
    priceAmd: 12300,
    category: "outdoor-play",
    subcategory: "active-play",
    ageRange: "3-6",
    materials: ["Wood", "Sisal"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/hoopla-ring-toss-game-1.jpg", alt: "Hoopla ring toss game with sisal rings" }],
    inStock: true,
    sku: "56801",
    relatedSlugs: ["target-throwing-game", "balance-board-wave"],
    dimensions: "49 x 49 x 11.5 cm",
  },
  {
    slug: "balance-board-wave",
    name: "Balance Board, Wave",
    nameHy: "Հավասարակշռության տախտակ, ալիք",
    nameRu: "Балансборд «Волна»",
    shortDescription: "Half-pipe wooden balance board that doubles as ramp, slide, and rocker.",
    shortDescriptionHy: "Կիսագլան փայտյա հավասարակշռության տախտակ, որը կրկնակի ծառայում է որպես թեքահարթակ, սահադիրք և օրորոց։",
    shortDescriptionRu: "Балансборд-полутруба, служащий одновременно рампой, горкой и качалкой.",
    description:
      "This flexible half-pipe board stimulates balance, coordination, and concentration, and doubles as a car ramp, slide, or rocking board when the imagination takes over. Rated for up to 150 kg, with a felt-coated underside that's gentle on floors.",
    descriptionHy:
      "Այս ճկուն կիսագլան տախտակը խթանում է հավասարակշռությունը, համակարգումն ու կենտրոնացումը, և կրկնակի ծառայում է որպես մեքենայի թեքահարթակ, սահադիրք կամ օրորվող տախտակ, երբ երևակայությունը գործի է անցնում։ Դիմացկուն է մինչև 150 կգ, և զգայուն է հատակների նկատմամբ իր բրդյա ծածկույթի շնորհիվ։",
    descriptionRu:
      "Эта гибкая полутрубчатая доска развивает баланс, координацию и концентрацию, а заодно служит рампой для машинок, горкой или качалкой, когда включается фантазия. Выдерживает нагрузку до 150 кг, войлочное покрытие снизу бережно к полу.",
    priceAmd: 35000,
    category: "outdoor-play",
    subcategory: "active-play",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/balance-board-wave-1-v2.jpg", alt: "Wooden wave balance board" }, { src: "/images/products/balance-board-wave-2-v2.jpg", alt: "Child balancing on the wave balance board at home" }, { src: "/images/products/balance-board-wave-3-v2.jpg", alt: "Child playing on the wave balance board in a play tent" }, { src: "/images/products/balance-board-wave-4-v2.jpg", alt: "Child using the wave balance board indoors" }, { src: "/images/products/balance-board-wave-5-v2.jpg", alt: "Wave balance board with wooden toy animals nearby" }],
    inStock: true,
    sku: "59968",
    newArrival: true,
    relatedSlugs: ["hoopla-ring-toss-game", "target-throwing-game"],
    dimensions: "82 x 30 x 1.8 cm",
  },
  {
    slug: "target-throwing-game",
    name: "Target Throwing Game for Young and Old",
    nameHy: "Նպատակային նետման խաղ՝ երիտասարդների ու մեծերի համար",
    nameRu: "Игра-мишень для метания, для детей и взрослых",
    shortDescription: "Two-difficulty wooden throwing game the whole family can play together.",
    shortDescriptionHy: "Երկու բարդության մակարդակով փայտյա նետման խաղ, որը ողջ ընտանիքը կարող է խաղալ միասին։",
    shortDescriptionRu: "Деревянная игра на меткость с двумя уровнями сложности для всей семьи.",
    description:
      "Great fun with two levels of difficulty, this throwing game lets the youngest players test their aim right alongside the grown-ups. A lightweight, portable game built for backyard afternoons and family tournaments.",
    descriptionHy:
      "Մեծ հաճույք՝ երկու բարդության մակարդակով, այս նետման խաղը թույլ է տալիս ամենափոքր խաղացողներին փորձարկել իրենց նշանառությունը մեծերի հետ միասին։ Թեթևակշիռ, տեղափոխելի խաղ՝ բակի կեսօրերի և ընտանեկան մրցաշարերի համար։",
    descriptionRu:
      "Отличная забава с двумя уровнями сложности — эта игра на меткость позволяет самым маленьким игрокам испытать свой глазомер наравне со взрослыми. Лёгкая, переносная игра для дворовых вечеров и семейных турниров.",
    priceAmd: 18000,
    category: "outdoor-play",
    subcategory: "active-play",
    ageRange: "3-6",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/target-throwing-game-1.jpg", alt: "Wooden target throwing game" }, { src: "/images/products/target-throwing-game-2.jpg", alt: "Target throwing game with an alternate ring color set" }],
    inStock: true,
    sku: "56330",
    relatedSlugs: ["hoopla-ring-toss-game", "balance-board-wave"],
    dimensions: "47.5 x 36 x 2.9 cm",
  },
  {
    slug: "garden-tools-set",
    name: "Garden Tools Set, Spring",
    nameHy: "Այգեգործական գործիքների հավաքածու, գարուն",
    nameRu: "Набор садовых инструментов «Весна»",
    shortDescription: "Three-piece children's garden set with two shovels and a rake.",
    shortDescriptionHy: "Երեք կտորից բաղկացած երեխաների այգեգործական հավաքածու՝ երկու բահով և փոցխով։",
    shortDescriptionRu: "Детский набор из трёх садовых инструментов — две лопатки и грабли.",
    description:
      "Two shovels and a rake in an adorable child-sized design, ready for helping out on the balcony or in the garden all spring and summer. Wooden handles and no sharp edges make real gardening safe for little helpers.",
    descriptionHy:
      "Երկու բահ և փոցխ՝ երեխայի չափի հմայիչ դիզայնով, պատրաստ օգնելու պատշգամբում կամ այգում ողջ գարուն ու ամառ։ Փայտյա բռնակները և սուր եզրերի բացակայությունը իրական այգեգործությունը դարձնում են անվտանգ փոքրիկ օգնականների համար։",
    descriptionRu:
      "Две лопатки и грабли в очаровательном детском формате — готовы помогать на балконе или в саду всю весну и лето. Деревянные ручки и отсутствие острых краёв делают настоящее садоводство безопасным для маленьких помощников.",
    priceAmd: 6200,
    category: "outdoor-play",
    subcategory: "active-play",
    ageRange: "3-6",
    materials: ["Wood", "Metal"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/garden-tools-set-1-v2.jpg", alt: "Children's garden tools set with shovels and rake" }, { src: "/images/products/garden-tools-set-2.jpg", alt: "Garden tools set laid out without packaging" }, { src: "/images/products/garden-tools-set-3.jpg", alt: "Garden tools set in use in soil outdoors" }],
    inStock: true,
    sku: "63875",
    relatedSlugs: ["garden-tools-bucket-snail", "target-throwing-game"],
    dimensions: "20.5 x 7 x 5 cm",
  },
  {
    slug: "garden-tools-bucket-snail",
    name: "Garden Tools Bucket, Snail Design",
    nameHy: "Այգեգործական գործիքների դույլ, խխունջի դիզայն",
    nameRu: "Ведёрко с садовыми инструментами «Улитка»",
    shortDescription: "Sturdy tin bucket with spade, rake, and digging fork for little gardeners.",
    shortDescriptionHy: "Ամուր թիթեղյա դույլ՝ բահով, փոցխով և փորման պատառաքաղով փոքրիկ այգեգործների համար։",
    shortDescriptionRu: "Прочное жестяное ведёрко с совком, граблями и вилами для маленьких садоводов.",
    description:
      "A colorful tin bucket carries a spade, rake, and digging fork decorated with a cheerful snail motif — everything a little gardener needs for hours of curious, hands-in-the-dirt outdoor fun.",
    descriptionHy:
      "Գունավոր թիթեղյա դույլը կրում է բահ, փոցխ և փորման պատառաքաղ՝ զարդարված ուրախ խխունջի մոտիվով․ ամեն ինչ, ինչ անհրաժեշտ է փոքրիկ այգեգործին հողի մեջ ձեռքերով երկար ժամեր հետաքրքրասեր բացօթյա խաղի համար։",
    descriptionRu:
      "Яркое жестяное ведёрко несёт совок, грабли и вилы, украшенные весёлым мотивом улитки — всё, что нужно маленькому садоводу для долгих часов любопытной игры на улице, с руками в земле.",
    priceAmd: 7200,
    category: "outdoor-play",
    subcategory: "active-play",
    ageRange: "3-6",
    materials: ["Wood", "Metal"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/garden-tools-bucket-snail-1.jpg", alt: "Garden tools bucket with snail design" }, { src: "/images/products/garden-tools-bucket-snail-2.jpg", alt: "Garden tools bucket with snail design, a different angle" }],
    inStock: true,
    sku: "63870",
    relatedSlugs: ["garden-tools-set", "hoopla-ring-toss-game"],
    dimensions: "13.8 x 13.8 x 13 cm",
  },
  {
    slug: "touch-ring-rainbow-ball",
    name: "Touch Ring, Elastic Rainbow Ball",
    nameHy: "Հպումային օղակ, առաձգական ծիածան գնդակ",
    nameRu: "Тактильное кольцо «Радужный шар»",
    shortDescription: "Elastic wooden touch ring shaped like a colorful ball, sized for tiny hands.",
    shortDescriptionHy: "Առաձգական փայտյա հպումային օղակ՝ գունավոր գնդակի ձևով, հարմարեցված փոքրիկ ձեռքերի համար։",
    shortDescriptionRu: "Эластичное деревянное тактильное кольцо в виде яркого шара, по размеру маленьких ручек.",
    description:
      "Touch rings are indispensable for a baby's hand — this rainbow-toned ball shape triggers the natural grip reflex and rewards exploring fingers with new sensations as they discover their environment.",
    descriptionHy:
      "Հպումային օղակները անփոխարինելի են երեխայի ձեռքի համար․ այս ծիածանագույն գնդակի ձևը միացնում է բնական բռնման ռեֆլեքսը և հատուցում է հետազոտող մատներին նոր զգացողություններով, երբ նրանք բացահայտում են իրենց միջավայրը։",
    descriptionRu:
      "Тактильные кольца незаменимы для детской ручки — этот шар в радужных тонах запускает естественный хватательный рефлекс и дарит исследующим пальчикам новые ощущения при знакомстве с окружающим миром.",
    priceAmd: 5300,
    category: "baby-toddler",
    subcategory: "rattles-teethers",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/touch-ring-rainbow-ball-1.jpg", alt: "Elastic wooden touch ring, rainbow ball shape" }],
    inStock: true,
    sku: "65326",
    relatedSlugs: ["touch-ring-star", "star-dance-mobile"],
    dimensions: "8 x 8 x 8 cm",
  },
  {
    slug: "touch-ring-star",
    name: "Touch Ring, Elastic Star",
    nameHy: "Հպումային օղակ, առաձգական աստղ",
    nameRu: "Тактильное кольцо «Звезда»",
    shortDescription: "Star-shaped touch ring with wood and silicone beads for extra sensory stimulation.",
    shortDescriptionHy: "Աստղաձև հպումային օղակ՝ փայտե ու սիլիկոնե հատիկներով՝ լրացուցիչ զգայական խթանման համար։",
    shortDescriptionRu: "Тактильное кольцо в форме звезды с деревянными и силиконовыx бусинами для дополнительной сенсорной стимуляции.",
    description:
      "Wood-and-silicone touch rings trigger the grasping reflex and support developmental fine-motor progress, while the interplay of smooth and textured surfaces also supports early language development through mouthing and touch exploration. Lovingly engraved wooden parts complete the design.",
    descriptionHy:
      "Փայտից ու սիլիկոնից հպումային օղակները միացնում են բռնման ռեֆլեքսը և աջակցում նուրբ շարժողական զարգացմանը, մինչդեռ հարթ և հյուսվածքային մակերևույթների համադրությունը նաև աջակցում է վաղ լեզվի զարգացմանը՝ բերանով ու հպումով հետազոտության միջոցով։ Սիրով փորագրված փայտյա մասերը լրացնում են դիզայնը։",
    descriptionRu:
      "Тактильные кольца из дерева и силикона запускают хватательный рефлекс и поддерживают развитие мелкой моторики, а сочетание гладких и текстурных поверхностей помогает и раннему речевому развитию через исследование ртом и на ощупь. Дизайн дополняют деревянные детали с изящной гравировкой.",
    priceAmd: 3200,
    category: "baby-toddler",
    subcategory: "rattles-teethers",
    ageRange: "0-3",
    materials: ["Wood", "Silicone"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/touch-ring-star-1.jpg", alt: "Elastic wooden touch ring, star shape" }],
    inStock: true,
    sku: "65242",
    relatedSlugs: ["touch-ring-rainbow-ball", "star-dance-mobile"],
    dimensions: "9 x 9 x 9 cm",
  },
  {
    slug: "exploration-building-blocks",
    name: "Exploration Building Blocks",
    nameHy: "Հետազոտական կառուցողական խորանարդիկներ",
    nameRu: "Строительные блоки «Исследование»",
    shortDescription: "Building blocks with a built-in kaleidoscope, beads, and balls for extra sensory play.",
    shortDescriptionHy: "Կառուցողական խորանարդիկներ՝ ներկառուցված կալեիդոսկոպով, հատիկներով և գնդիկներով՝ լրացուցիչ զգայական խաղի համար։",
    shortDescriptionRu: "Строительные блоки со встроенным калейдоскопом, бусинами и шариками для дополнительной сенсорной игры.",
    description:
      "Our explorer building blocks offer plenty to marvel at: alongside classic shapes and colors for basic building, the set folds in sensory elements like a kaleidoscope, beads, and balls that add tactile and visual stimulation to every building session.",
    descriptionHy:
      "Մեր հետազոտող կառուցողական խորանարդիկները շատ բան ունեն զարմացնելու՝ դասական ձևերի ու գույների կողքին, հավաքածուն ներառում է զգայական տարրեր, ինչպիսիք են կալեիդոսկոպը, հատիկներն ու գնդիկները, որոնք ավելացնում են շոշափելի ու տեսողական խթանում ամեն կառուցման ընթացքում։",
    descriptionRu:
      "Наши блоки-исследователи дарят немало открытий: помимо классических форм и цветов для строительства, набор включает сенсорные элементы — калейдоскоп, бусины и шарики, которые добавляют тактильную и визуальную стимуляцию каждой игровой сессии.",
    priceAmd: 11000,
    category: "baby-toddler",
    subcategory: "first-blocks",
    ageRange: "0-3",
    materials: ["Wood", "Metal"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/exploration-building-blocks-1-v2.jpg", alt: "Exploration building blocks with kaleidoscope element" }, { src: "/images/products/exploration-building-blocks-2.jpg", alt: "Exploration building blocks arranged in a decorative tray" }, { src: "/images/products/exploration-building-blocks-3.jpg", alt: "Exploration building blocks stacked into a small tower" }, { src: "/images/products/exploration-building-blocks-4.jpg", alt: "Exploration building blocks arranged with a toy car" }],
    inStock: true,
    sku: "58346",
    featured: true,
    relatedSlugs: ["colorful-building-block-box", "little-rainbow-building-blocks"],
    dimensions: "18 x 18 x 4.3 cm",
  },
  {
    slug: "baby-gym-walking-train",
    name: "Baby Gym & Walking Train",
    nameHy: "Երեխայի մարմնամարզական և քայլելու գնացք",
    nameRu: "Детский спорткомплекс и ходунки-паровозик",
    shortDescription: "3-in-1 baby gym, learn-to-walk aid, and coat rack that grows with your child.",
    shortDescriptionHy: "3-ը-1-ում մարմնամարզական համալիր, քայլել սովորելու օգնական և հագուստի կախիչ, որը մեծանում է Ձեր երեխայի հետ միասին։",
    shortDescriptionRu: "3-в-1: спортивный комплекс, помощник для первых шагов и вешалка, растущие вместе с ребёнком.",
    description:
      "Six adjustable heights let this wooden frame grow from a tummy-time activity gym into a sturdy walking aid your toddler can push and hold onto for their very first steps. The side pieces even double as a coat rack once walking days are behind you.",
    descriptionHy:
      "Վեց կարգավորվող բարձրություններ թույլ են տալիս այս փայտյա շրջանակին աճել՝ որովայնի ժամանակի ակտիվության համալիրից մինչև ամուր քայլելու օգնական, որը Ձեր փոքրիկը կարող է հրել և բռնել իր առաջին քայլերի համար։ Կողային մասերը նույնիսկ կրկնակի ծառայում են որպես հագուստի կախիչ, երբ քայլելու օրերն արդեն հետևում են։",
    descriptionRu:
      "Шесть регулируемых уровней высоты позволяют этой деревянной раме расти вместе с ребёнком — от спортивного комплекса для занятий на животике до надёжного помощника, за который малыш держится, делая первые шаги. Боковые части даже служат вешалкой, когда время первых шагов останется позади.",
    priceAmd: 45000,
    category: "educational",
    subcategory: "early-learning",
    ageRange: "0-3",
    materials: ["Solid wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/baby-gym-walking-train-1-v2.jpg", alt: "Wooden baby gym and walking train frame" }],
    inStock: true,
    sku: "65318",
    featured: true,
    newArrival: true,
    relatedSlugs: ["hammer-bench", "wooden-bead-maze"],
    dimensions: "67 x 55 x 53 cm",
  },
  {
    slug: "music-box-horse",
    name: "Music Box Horse with Drawer",
    nameHy: "Երաժշտական տուփ-ձի՝ դարակով",
    nameRu: "Музыкальная шкатулка «Лошадка» с ящичком",
    shortDescription: "Horse-shaped music box with hidden compartments that plays Swan Lake.",
    shortDescriptionHy: "Ձիու տեսքով երաժշտական տուփ՝ թաքնված խորշերով, որը նվագում է «Կարապի լիճը»։",
    shortDescriptionRu: "Музыкальная шкатулка в форме лошадки со скрытыми отделениями, играющая мелодию из «Лебединого озера».",
    description:
      "A must for every young horse lover, this charming music box opens to the melody of Swan Lake and hides several small compartments for tiny treasures. As much a keepsake as a toy — the kind of thing kept long after playtime.",
    descriptionHy:
      "Անհրաժեշտ իր ամեն մի փոքրիկ ձիու սիրահարի համար, այս հմայիչ երաժշտական տուփը բացվում է «Կարապի լիճ»-ի մեղեդիով և թաքցնում մի քանի փոքրիկ խորշեր՝ մանրիկ գանձերի համար։ Նույնքան հուշանվեր է, որքան խաղալիք․ այն ինչ պահվում է երկար ժամանակ խաղից հետո։",
    descriptionRu:
      "Настоящая находка для юных любителей лошадей: эта очаровательная музыкальная шкатулка открывается под мелодию «Лебединого озера» и прячет несколько маленьких отделений для крошечных сокровищ. Столько же сувенир, сколько игрушка — из тех вещей, что хранят ещё долго.",
    priceAmd: 14800,
    category: "wooden-toys",
    subcategory: "musical",
    ageRange: "3-6",
    materials: ["Cardboard", "Wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/music-box-horse-1.jpg", alt: "Horse-shaped music box with drawer" }, { src: "/images/products/music-box-horse-2.jpg", alt: "Music box horse shown closed, showing the painted exterior" }],
    inStock: true,
    sku: "60064",
    relatedSlugs: ["rainbow-xylophone", "wooden-rocking-horse"],
    dimensions: "19.3 x 11 x 9.8 cm",
  },
  {
    slug: "star-dance-mobile",
    name: "Star Dance Crib Mobile",
    nameHy: "«Աստղերի պար» օրորոցի մոբիլ",
    nameRu: "Мобиль для кроватки «Танец звёзд»",
    shortDescription: "Handcrafted felt-wool star mobile that gently dances above the crib.",
    shortDescriptionHy: "Ձեռագործ բրդե զգացած աստղերով մոբիլ, որը մեղմորեն պարում է օրորոցի վրայում։",
    shortDescriptionRu: "Мобиль из фетра ручной работы со звёздами, мягко танцующими над кроваткой.",
    description:
      "Little felt-wool stars in vibrant purple, pink, yellow, and blue dance gently above the crib, catching a baby's eye and soothing them with slow, quiet motion. Handcrafted from fair-trade wool and easy to install wherever your baby plays or rests.",
    descriptionHy:
      "Փոքրիկ բրդե զգացած աստղերը՝ վառ մանուշակագույն, վարդագույն, դեղին ու կապույտ գույներով, մեղմորեն պարում են օրորոցի վրայում՝ գրավելով երեխայի հայացքը և հանգստացնելով նրան դանդաղ, հանգիստ շարժումով։ Ձեռագործ արդար առևտրի բրդից, հեշտ տեղադրվող ամենուր, որտեղ Ձեր երեխան խաղում կամ հանգստանում է։",
    descriptionRu:
      "Маленькие звёздочки из фетра — ярко-фиолетовые, розовые, жёлтые и голубые — мягко танцуют над кроваткой, привлекая взгляд малыша и убаюкивая его медленным, тихим движением. Изготовлены вручную из шерсти справедливой торговли, легко устанавливаются везде, где играет или отдыхает ваш малыш.",
    priceAmd: 9900,
    category: "baby-toddler",
    subcategory: "soft-toys",
    ageRange: "0-3",
    materials: ["Felt wool", "Wood"],
    safetyInfo: SAFETY_STANDARD,
    brand: "GOKI",
    images: [{ src: "/images/products/star-dance-mobile-1.jpg", alt: "Felt wool star crib mobile" }],
    inStock: true,
    sku: "52868",
    newArrival: true,
    relatedSlugs: ["touch-ring-rainbow-ball", "touch-ring-star"],
    dimensions: "54 x 24.5 x 24.5 cm",
  },
];

async function main() {
  console.log(`Seeding ${products.length} products...`);
  // update stays {} deliberately: this DB is shared with the live admin
  // panel, and staff may have edited stock/price/featured flags on a
  // product since it was first seeded. Re-running this script must not
  // clobber those. To push a source-of-truth edit (e.g. this file's
  // images/description/etc.) into an EXISTING row, write a one-off
  // script that calls prisma.product.update() for that slug directly —
  // don't rely on re-running this seed.
  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {},
      create: {
        slug: p.slug,
        sku: p.sku,
        name: p.name,
        nameHy: p.nameHy,
        nameRu: p.nameRu,
        shortDescription: p.shortDescription,
        shortDescriptionHy: p.shortDescriptionHy,
        shortDescriptionRu: p.shortDescriptionRu,
        description: p.description,
        descriptionHy: p.descriptionHy,
        descriptionRu: p.descriptionRu,
        priceAmd: p.priceAmd,
        compareAtPriceAmd: p.compareAtPriceAmd,
        category: p.category,
        subcategory: p.subcategory,
        ageRange: p.ageRange,
        brand: p.brand,
        materials: JSON.stringify(p.materials),
        safetyInfo: JSON.stringify(p.safetyInfo),
        images: JSON.stringify(p.images),
        relatedSlugs: p.relatedSlugs ? JSON.stringify(p.relatedSlugs) : null,
        inStock: p.inStock,
        featured: p.featured ?? false,
        bestseller: p.bestseller ?? false,
        newArrival: p.newArrival ?? false,
        dimensions: p.dimensions,
        weightGrams: p.weightGrams,
        careInstructions: p.careInstructions,
      },
    });
  }

  console.log("Seeding promo codes...");
  await prisma.promoCode.upsert({
    where: { code: "WELCOME5" },
    update: {},
    create: {
      code: "WELCOME5",
      percentOff: 5,
      description: "5% off your first order",
      descriptionHy: "5% զեղչ առաջին պատվերի համար",
      descriptionRu: "Скидка 5% на первый заказ",
      active: true,
    },
  });

  const adminCount = await prisma.adminUser.count();
  if (adminCount === 0) {
    const email = process.env.ADMIN_BOOTSTRAP_EMAIL;
    const password = process.env.ADMIN_BOOTSTRAP_PASSWORD;
    if (email && password) {
      console.log(`Creating first admin account (${email})...`);
      const passwordHash = await bcrypt.hash(password, 10);
      await prisma.adminUser.create({
        data: { email, passwordHash, name: "Admin", role: "manager" },
      });
    } else {
      console.warn(
        "No admin account exists and ADMIN_BOOTSTRAP_EMAIL/ADMIN_BOOTSTRAP_PASSWORD are not set — skipping. Set them in .env and re-run `npm run db:seed`."
      );
    }
  } else {
    console.log(`${adminCount} admin account(s) already exist — skipping bootstrap.`);
  }

  console.log("Done.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
